# A Small sampling of manufacturers to seed!
# To get the full list download https://github.com/bikeindex/resources/blob/master/manufacturers.csv
# You can upload the csv in admin section :)
# 
# 
# OG Test Manufacturers are commented out to get the whole list for now
# 
# Manufacturer.create(name: "Unknown", frame_maker: true)
# Manufacturer.create(name: "Other", frame_maker: true)
# Manufacturer.create(name: "Giant",  frame_maker: true, website: "http://www.giant-bicycles.com/")
# Manufacturer.create(name: "Yamaguchi",  frame_maker: true, website: "http://www.yamaguchibike.com/content/Index")
# Manufacturer.create(name: "Zipp Speed Weaponry", website: "http://www.zipp.com/")
# Manufacturer.create(name: "WeThePeople",  frame_maker: true, website: "http://www.wethepeoplebmx.de/bikes")
# Manufacturer.create(name: "Rivendell Bicycle Works",  frame_maker: true, website: "http://www.rivbike.com/")
# Manufacturer.create(name: "Soma",  frame_maker: true, website: "www.somafab.com")
# Manufacturer.create(name: "Fuji",  frame_maker: true, website: "http://www.fujibikes.com/")
# Manufacturer.create(name: "Schwinn",  frame_maker: true, website: "http://www.schwinnbikes.com/")
# Manufacturer.create(name: "Sram",  frame_maker: false, website: "http://www.sram.com")
# Manufacturer.create(name: "Doberman",  frame_maker: true, website: "https://www.facebook.com/DobermannBikes")
# Manufacturer.create(name: "Surly",  frame_maker: true, website: "http://surlybikes.com")
# Manufacturer.create(name: "Trek",  frame_maker: true, website: "http://www.trekbikes.com/us/en/")
# Manufacturer.create(name: "KHS",  frame_maker: true, website: "http://khsbicycles.com/")
# Manufacturer.create(name: "Jamis",  frame_maker: true, website: "http://www.jamisbikes.com/usa/index.html")
# Manufacturer.create(name: "Shimano",  frame_maker: false, website: "http://bike.shimano.com")
# Manufacturer.create(name: "Campagnolo",  frame_maker: false, website: "http://www.campagnolo.com/")


Manufacturer.create!(name: "24seven", frame_maker: true)
Manufacturer.create!(name: "3M", frame_maker: true)
Manufacturer.create!(name: "3T", frame_maker: true)
Manufacturer.create!(name: "3rd Eye", frame_maker: true)
Manufacturer.create!(name: "45North", frame_maker: true)
Manufacturer.create!(name: "4ZA", frame_maker: true)
Manufacturer.create!(name: "A-Class", frame_maker: true)
Manufacturer.create!(name: "A-bike", frame_maker: true)
Manufacturer.create!(name: "ABI", frame_maker: true)
Manufacturer.create!(name: "ACS", frame_maker: true)
Manufacturer.create!(name: "ALAN", frame_maker: true)
Manufacturer.create!(name: "AMF", frame_maker: true)
Manufacturer.create!(name: "Aardvark", frame_maker: true)
Manufacturer.create!(name: "Abici", frame_maker: true)
Manufacturer.create!(name: "Abus", frame_maker: true)
Manufacturer.create!(name: "Accelerade", frame_maker: true)
Manufacturer.create!(name: "Accell", frame_maker: true)
Manufacturer.create!(name: "Access", frame_maker: true)
Manufacturer.create!(name: "Acros", frame_maker: true)
Manufacturer.create!(name: "Adolphe Clément", frame_maker: true)
Manufacturer.create!(name: "Adventure Medical Kits", frame_maker: true)
Manufacturer.create!(name: "Aerofix Cycles", frame_maker: true)
Manufacturer.create!(name: "AheadSet", frame_maker: true)
Manufacturer.create!(name: "Aist Bicycles", frame_maker: true)
Manufacturer.create!(name: "Aladdin", frame_maker: true)
Manufacturer.create!(name: "Alcyon", frame_maker: true)
Manufacturer.create!(name: "Alex", frame_maker: true)
Manufacturer.create!(name: "Alexander Leutner & Co.", frame_maker: true)
Manufacturer.create!(name: "Alien Bikes", frame_maker: true)
Manufacturer.create!(name: "Alienation", frame_maker: true)
Manufacturer.create!(name: "Alite Designs", frame_maker: true)
Manufacturer.create!(name: "All City", frame_maker: true)
Manufacturer.create!(name: "Alldays & Onions", frame_maker: true)
Manufacturer.create!(name: "American Bicycle Company", frame_maker: true)
Manufacturer.create!(name: "American Classic", frame_maker: true)
Manufacturer.create!(name: "American Machine and Foundry", frame_maker: true)
Manufacturer.create!(name: "American Star Bicycle", frame_maker: true)
Manufacturer.create!(name: "And", frame_maker: true)
Manufacturer.create!(name: "Andiamo", frame_maker: true)
Manufacturer.create!(name: "Answer BMX", frame_maker: true)
Manufacturer.create!(name: "Answer Products", frame_maker: true)
Manufacturer.create!(name: "Apollo", frame_maker: true)
Manufacturer.create!(name: "Aqua Sphere", frame_maker: true)
Manufacturer.create!(name: "Aquamira", frame_maker: true)
Manufacturer.create!(name: "Arai", frame_maker: true)
Manufacturer.create!(name: "Argon 18", frame_maker: true)
Manufacturer.create!(name: "Asama", frame_maker: true)
Manufacturer.create!(name: "Asda", frame_maker: true)
Manufacturer.create!(name: "Assos", frame_maker: true)
Manufacturer.create!(name: "Atala", frame_maker: true)
Manufacturer.create!(name: "Atomlab", frame_maker: true)
Manufacturer.create!(name: "Author", frame_maker: true)
Manufacturer.create!(name: "Avanti", frame_maker: true)
Manufacturer.create!(name: "Aventón", frame_maker: true)
Manufacturer.create!(name: "Avid", frame_maker: true)
Manufacturer.create!(name: "Axiom", frame_maker: true)
Manufacturer.create!(name: "Axle Release", frame_maker: true)
Manufacturer.create!(name: "Aztec", frame_maker: true)
Manufacturer.create!(name: "Azzuri", frame_maker: true)
Manufacturer.create!(name: "BCA", frame_maker: true)
Manufacturer.create!(name: "BMC", frame_maker: true)
Manufacturer.create!(name: "BOB", frame_maker: true)
Manufacturer.create!(name: "BONT", frame_maker: true)
Manufacturer.create!(name: "BOX", frame_maker: true)
Manufacturer.create!(name: "BSD", frame_maker: true)
Manufacturer.create!(name: "BULLITT", frame_maker: true)
Manufacturer.create!(name: "Bacchetta", frame_maker: true)
Manufacturer.create!(name: "Backpacker's Pantry", frame_maker: true)
Manufacturer.create!(name: "Backward Circle", frame_maker: true)
Manufacturer.create!(name: "Bahco", frame_maker: true)
Manufacturer.create!(name: "Bailey", frame_maker: true)
Manufacturer.create!(name: "Baladeo", frame_maker: true)
Manufacturer.create!(name: "Banjo Brothers", frame_maker: true)
Manufacturer.create!(name: "Banshee bikes", frame_maker: true)
Manufacturer.create!(name: "Bar Mitts", frame_maker: true)
Manufacturer.create!(name: "Basso", frame_maker: true)
Manufacturer.create!(name: "Batavus", frame_maker: true)
Manufacturer.create!(name: "BeOne", frame_maker: true)
Manufacturer.create!(name: "Beater Bikes", frame_maker: true)
Manufacturer.create!(name: "Beistegui Hermanos", frame_maker: true)
Manufacturer.create!(name: "Bellwether", frame_maker: true)
Manufacturer.create!(name: "Bergamont", frame_maker: true)
Manufacturer.create!(name: "Bertucci", frame_maker: true)
Manufacturer.create!(name: "Bianchi", frame_maker: true)
Manufacturer.create!(name: "Bickerton", frame_maker: true)
Manufacturer.create!(name: "Bicycle Research", frame_maker: true)
Manufacturer.create!(name: "Big Agnes Inc", frame_maker: true)
Manufacturer.create!(name: "Bike Fit Systems", frame_maker: true)
Manufacturer.create!(name: "Bike Friday", frame_maker: true)
Manufacturer.create!(name: "Bike Mielec", frame_maker: true)
Manufacturer.create!(name: "Bike Ribbon", frame_maker: true)
Manufacturer.create!(name: "Bike-Aid", frame_maker: true)
Manufacturer.create!(name: "Bike-Eye", frame_maker: true)
Manufacturer.create!(name: "Bike-O-Vision", frame_maker: true)
Manufacturer.create!(name: "BikeE recumbents", frame_maker: true)
Manufacturer.create!(name: "Bikes Belong", frame_maker: true)
Manufacturer.create!(name: "Bikeverywhere", frame_maker: true)
Manufacturer.create!(name: "Bilenky Cycle Works", frame_maker: true)
Manufacturer.create!(name: "Biomega", frame_maker: true)
Manufacturer.create!(name: "BionX", frame_maker: true)
Manufacturer.create!(name: "Birdy", frame_maker: true)
Manufacturer.create!(name: "Biria", frame_maker: true)
Manufacturer.create!(name: "Birmingham Small Arms Company", frame_maker: true)
Manufacturer.create!(name: "Black Diamond", frame_maker: true)
Manufacturer.create!(name: "Black Market", frame_maker: true)
Manufacturer.create!(name: "Black Sheep Bikes", frame_maker: true)
Manufacturer.create!(name: "Boardman Bikes", frame_maker: true)
Manufacturer.create!(name: "Bobbin", frame_maker: true)
Manufacturer.create!(name: "BodyGlide", frame_maker: true)
Manufacturer.create!(name: "Boeshield", frame_maker: true)
Manufacturer.create!(name: "Bohemian Bicycles", frame_maker: true)
Manufacturer.create!(name: "Bondhus", frame_maker: true)
Manufacturer.create!(name: "Bonk Breaker", frame_maker: true)
Manufacturer.create!(name: "Boreas Gear", frame_maker: true)
Manufacturer.create!(name: "Borile", frame_maker: true)
Manufacturer.create!(name: "Bottecchia", frame_maker: true)
Manufacturer.create!(name: "Boulder Bicycles", frame_maker: true)
Manufacturer.create!(name: "Bradbury Motor Cycles", frame_maker: true)
Manufacturer.create!(name: "Brannock Device Co", frame_maker: true)
Manufacturer.create!(name: "Brasil & Movimento", frame_maker: true)
Manufacturer.create!(name: "Brave Soldier", frame_maker: true)
Manufacturer.create!(name: "Breezer", frame_maker: true)
Manufacturer.create!(name: "Breezer Bikes", frame_maker: true)
Manufacturer.create!(name: "Brennabor", frame_maker: true)
Manufacturer.create!(name: "Bridgestone", frame_maker: true)
Manufacturer.create!(name: "British Eagle", frame_maker: true)
Manufacturer.create!(name: "Brompton Bicycle", frame_maker: true)
Manufacturer.create!(name: "Brooklyn Bicycle Co.", frame_maker: true)
Manufacturer.create!(name: "Brooks England LTD.", frame_maker: true)
Manufacturer.create!(name: "Brunswick Corporation", frame_maker: true)
Manufacturer.create!(name: "Brush Research", frame_maker: true)
Manufacturer.create!(name: "Buff", frame_maker: true)
Manufacturer.create!(name: "Burley", frame_maker: true)
Manufacturer.create!(name: "Burley Design", frame_maker: true)
Manufacturer.create!(name: "Bushnell", frame_maker: true)
Manufacturer.create!(name: "Buzzy's", frame_maker: true)
Manufacturer.create!(name: "CCM", frame_maker: true)
Manufacturer.create!(name: "CDI Torque Products", frame_maker: true)
Manufacturer.create!(name: "CHUMBA Racing", frame_maker: true)
Manufacturer.create!(name: "CRUD", frame_maker: true)
Manufacturer.create!(name: "CST", frame_maker: true)
Manufacturer.create!(name: "CVLN (Civilian)", frame_maker: true)
Manufacturer.create!(name: "CX Tape", frame_maker: true)
Manufacturer.create!(name: "Caffelatex", frame_maker: true)
Manufacturer.create!(name: "Calcott Brothers", frame_maker: true)
Manufacturer.create!(name: "Calfee Design", frame_maker: true)
Manufacturer.create!(name: "California Springs", frame_maker: true)
Manufacturer.create!(name: "Caloi", frame_maker: true)
Manufacturer.create!(name: "Camelbak", frame_maker: true)
Manufacturer.create!(name: "Camillus", frame_maker: true)
Manufacturer.create!(name: "Campagnolo", frame_maker: true)
Manufacturer.create!(name: "Campion Cycle Company", frame_maker: true)
Manufacturer.create!(name: "Cane Creek", frame_maker: true)
Manufacturer.create!(name: "Cannondale", frame_maker: true)
Manufacturer.create!(name: "Canyon bicycles", frame_maker: true)
Manufacturer.create!(name: "Carmichael Training Systems", frame_maker: true)
Manufacturer.create!(name: "Carrera bicycles", frame_maker: true)
Manufacturer.create!(name: "CatEye", frame_maker: true)
Manufacturer.create!(name: "Catrike", frame_maker: true)
Manufacturer.create!(name: "Centurion", frame_maker: true)
Manufacturer.create!(name: "CeramicSpeed", frame_maker: true)
Manufacturer.create!(name: "Cervélo", frame_maker: true)
Manufacturer.create!(name: "Chadwick", frame_maker: true)
Manufacturer.create!(name: "Challenge", frame_maker: true)
Manufacturer.create!(name: "Charge", frame_maker: true)
Manufacturer.create!(name: "Chase", frame_maker: true)
Manufacturer.create!(name: "Chater-Lea", frame_maker: true)
Manufacturer.create!(name: "Chicago Bicycle Company", frame_maker: true)
Manufacturer.create!(name: "Chris King", frame_maker: true)
Manufacturer.create!(name: "Chromag", frame_maker: true)
Manufacturer.create!(name: "Cignal", frame_maker: true)
Manufacturer.create!(name: "Cilo", frame_maker: true)
Manufacturer.create!(name: "Cinelli", frame_maker: true)
Manufacturer.create!(name: "Citizen Bike", frame_maker: true)
Manufacturer.create!(name: "City Bicycles Company", frame_maker: true)
Manufacturer.create!(name: "Civia", frame_maker: true)
Manufacturer.create!(name: "Clark-Kent", frame_maker: true)
Manufacturer.create!(name: "Claud Butler", frame_maker: true)
Manufacturer.create!(name: "Clean Bottle", frame_maker: true)
Manufacturer.create!(name: "Clement", frame_maker: true)
Manufacturer.create!(name: "Cloud Nine", frame_maker: true)
Manufacturer.create!(name: "Club Roost", frame_maker: true)
Manufacturer.create!(name: "Co-Motion Cycles", frame_maker: true)
Manufacturer.create!(name: "Coker Tire", frame_maker: true)
Manufacturer.create!(name: "Colnago", frame_maker: true)
Manufacturer.create!(name: "Competition Cycles Services", frame_maker: true)
Manufacturer.create!(name: "Condor", frame_maker: true)
Manufacturer.create!(name: "Conor", frame_maker: true)
Manufacturer.create!(name: "Continental", frame_maker: true)
Manufacturer.create!(name: "Contour Sport", frame_maker: true)
Manufacturer.create!(name: "Cook Bros. Racing", frame_maker: true)
Manufacturer.create!(name: "Cooper Bikes", frame_maker: true)
Manufacturer.create!(name: "Corima", frame_maker: true)
Manufacturer.create!(name: "Cortina Cycles", frame_maker: true)
Manufacturer.create!(name: "Craft", frame_maker: true)
Manufacturer.create!(name: "Crank Brothers", frame_maker: true)
Manufacturer.create!(name: "Crazy Creek", frame_maker: true)
Manufacturer.create!(name: "Create", frame_maker: true)
Manufacturer.create!(name: "Crescent Moon", frame_maker: true)
Manufacturer.create!(name: "Critical Cycles", frame_maker: true)
Manufacturer.create!(name: "Cube", frame_maker: true)
Manufacturer.create!(name: "CueClip", frame_maker: true)
Manufacturer.create!(name: "Cult", frame_maker: true)
Manufacturer.create!(name: "Currys", frame_maker: true)
Manufacturer.create!(name: "Cycle Dog", frame_maker: true)
Manufacturer.create!(name: "Cycle Force Group", frame_maker: true)
Manufacturer.create!(name: "Cycle Stuff", frame_maker: true)
Manufacturer.create!(name: "CycleAware", frame_maker: true)
Manufacturer.create!(name: "CycleOps", frame_maker: true)
Manufacturer.create!(name: "CyclePro", frame_maker: true)
Manufacturer.create!(name: "Cycles Devinci", frame_maker: true)
Manufacturer.create!(name: "Cycles Follis", frame_maker: true)
Manufacturer.create!(name: "Cycleurope", frame_maker: true)
Manufacturer.create!(name: "Cyclo", frame_maker: true)
Manufacturer.create!(name: "Cycloc", frame_maker: true)
Manufacturer.create!(name: "Cyfac", frame_maker: true)
Manufacturer.create!(name: "CygoLite", frame_maker: true)
Manufacturer.create!(name: "Cytosport", frame_maker: true)
Manufacturer.create!(name: "DAJO", frame_maker: true)
Manufacturer.create!(name: "DIG BMX", frame_maker: true)
Manufacturer.create!(name: "DMR Bikes", frame_maker: true)
Manufacturer.create!(name: "DNP", frame_maker: true)
Manufacturer.create!(name: "DT Swiss", frame_maker: true)
Manufacturer.create!(name: "DZ Nuts", frame_maker: true)
Manufacturer.create!(name: "Da Bomb Bikes", frame_maker: true)
Manufacturer.create!(name: "Dahon", frame_maker: true)
Manufacturer.create!(name: "Dawes Cycles", frame_maker: true)
Manufacturer.create!(name: "De Rosa", frame_maker: true)
Manufacturer.create!(name: "DeBernardi", frame_maker: true)
Manufacturer.create!(name: "DeFeet", frame_maker: true)
Manufacturer.create!(name: "Deco", frame_maker: true)
Manufacturer.create!(name: "Deda Elementi", frame_maker: true)
Manufacturer.create!(name: "Deity", frame_maker: true)
Manufacturer.create!(name: "Delta", frame_maker: true)
Manufacturer.create!(name: "Deluxe", frame_maker: true)
Manufacturer.create!(name: "Demolition", frame_maker: true)
Manufacturer.create!(name: "Den Beste Sykkel", frame_maker: true)
Manufacturer.create!(name: "Derby Cycle", frame_maker: true)
Manufacturer.create!(name: "Dermatone", frame_maker: true)
Manufacturer.create!(name: "Dero", frame_maker: true)
Manufacturer.create!(name: "Deuter", frame_maker: true)
Manufacturer.create!(name: "Di Blasi Industriale", frame_maker: true)
Manufacturer.create!(name: "Dia-Compe", frame_maker: true)
Manufacturer.create!(name: "DiaTech", frame_maker: true)
Manufacturer.create!(name: "Diamant", frame_maker: true)
Manufacturer.create!(name: "Diamondback", frame_maker: true)
Manufacturer.create!(name: "Dicta", frame_maker: true)
Manufacturer.create!(name: "Dimension", frame_maker: true)
Manufacturer.create!(name: "Discwing", frame_maker: true)
Manufacturer.create!(name: "Doberman", frame_maker: true)
Manufacturer.create!(name: "Dodici Milano", frame_maker: true)
Manufacturer.create!(name: "Dolan", frame_maker: true)
Manufacturer.create!(name: "Dorel Industries", frame_maker: true)
Manufacturer.create!(name: "Dual Eyewear", frame_maker: true)
Manufacturer.create!(name: "Dualco", frame_maker: true)
Manufacturer.create!(name: "Dunelt Motorcycles", frame_maker: true)
Manufacturer.create!(name: "Dynacraft BSC", frame_maker: true)
Manufacturer.create!(name: "Dyno", frame_maker: true)
Manufacturer.create!(name: "E-Case", frame_maker: true)
Manufacturer.create!(name: "E. C. Stearns Bicycle Agency", frame_maker: true)
Manufacturer.create!(name: "EBC", frame_maker: true)
Manufacturer.create!(name: "EK USA", frame_maker: true)
Manufacturer.create!(name: "ENVE Composites", frame_maker: true)
Manufacturer.create!(name: "ESI", frame_maker: true)
Manufacturer.create!(name: "EVS Sports", frame_maker: true)
Manufacturer.create!(name: "Eagle Bicycle Manufacturing Company manufacturing-company", frame_maker: true)
Manufacturer.create!(name: "Eagles Nest Outfitters", frame_maker: true)
Manufacturer.create!(name: "East Germany", frame_maker: true)
Manufacturer.create!(name: "Eastern", frame_maker: true)
Manufacturer.create!(name: "Ebisu", frame_maker: true)
Manufacturer.create!(name: "Eddy Merckx", frame_maker: true)
Manufacturer.create!(name: "Edinburgh Bicycle Co-operative operative", frame_maker: true)
Manufacturer.create!(name: "EighthInch", frame_maker: true)
Manufacturer.create!(name: "Electra Bicycle Company", frame_maker: true)
Manufacturer.create!(name: "Elevn Technologies", frame_maker: true)
Manufacturer.create!(name: "Elite SRL", frame_maker: true)
Manufacturer.create!(name: "Ellis Briggs", frame_maker: true)
Manufacturer.create!(name: "Ellsworth Handcrafted Bicycles bicycles", frame_maker: true)
Manufacturer.create!(name: "Emilio Bozzi", frame_maker: true)
Manufacturer.create!(name: "Endurance Films", frame_maker: true)
Manufacturer.create!(name: "Enduro", frame_maker: true)
Manufacturer.create!(name: "Endurox", frame_maker: true)
Manufacturer.create!(name: "Energizer", frame_maker: true)
Manufacturer.create!(name: "Enigma Titanium", frame_maker: true)
Manufacturer.create!(name: "Epic", frame_maker: true)
Manufacturer.create!(name: "Ergon", frame_maker: true)
Manufacturer.create!(name: "Esbit", frame_maker: true)
Manufacturer.create!(name: "Euro Asia Imports (EAI)", frame_maker: true)
Manufacturer.create!(name: "Europa", frame_maker: true)
Manufacturer.create!(name: "Eveready", frame_maker: true)
Manufacturer.create!(name: "Evil", frame_maker: true)
Manufacturer.create!(name: "Excelsior Motor Company", frame_maker: true)
Manufacturer.create!(name: "Excess Components", frame_maker: true)
Manufacturer.create!(name: "Exustar", frame_maker: true)
Manufacturer.create!(name: "FBM", frame_maker: true)
Manufacturer.create!(name: "FSA (Full Speed Ahead)", frame_maker: true)
Manufacturer.create!(name: "Failure", frame_maker: true)
Manufacturer.create!(name: "Fairdale", frame_maker: true)
Manufacturer.create!(name: "Falcon", frame_maker: true)
Manufacturer.create!(name: "Falcon Cycles", frame_maker: true)
Manufacturer.create!(name: "Fast Wax", frame_maker: true)
Manufacturer.create!(name: "Fat City Cycles", frame_maker: true)
Manufacturer.create!(name: "Fatback", frame_maker: true)
Manufacturer.create!(name: "Federal", frame_maker: true)
Manufacturer.create!(name: "Felt", frame_maker: true)
Manufacturer.create!(name: "FiberFix", frame_maker: true)
Manufacturer.create!(name: "Fiction", frame_maker: true)
Manufacturer.create!(name: "Field", frame_maker: true)
Manufacturer.create!(name: "Finish Line", frame_maker: true)
Manufacturer.create!(name: "Finite", frame_maker: true)
Manufacturer.create!(name: "Firenze", frame_maker: true)
Manufacturer.create!(name: "Firmstrong", frame_maker: true)
Manufacturer.create!(name: "First Endurance", frame_maker: true)
Manufacturer.create!(name: "Fit bike Co.", frame_maker: true)
Manufacturer.create!(name: "Fizik", frame_maker: true)
Manufacturer.create!(name: "Fleet Velo", frame_maker: true)
Manufacturer.create!(name: "Fleetwing", frame_maker: true)
Manufacturer.create!(name: "Flybikes", frame_maker: true)
Manufacturer.create!(name: "Flying Pigeon", frame_maker: true)
Manufacturer.create!(name: "Flying Scot", frame_maker: true)
Manufacturer.create!(name: "Focale44", frame_maker: true)
Manufacturer.create!(name: "Focus", frame_maker: true)
Manufacturer.create!(name: "Foggle", frame_maker: true)
Manufacturer.create!(name: "Fokhan", frame_maker: true)
Manufacturer.create!(name: "Folmer & Schwing", frame_maker: true)
Manufacturer.create!(name: "Fondriest", frame_maker: true)
Manufacturer.create!(name: "Forge Bikes", frame_maker: true)
Manufacturer.create!(name: "Formula", frame_maker: true)
Manufacturer.create!(name: "Foundry Cycles", frame_maker: true)
Manufacturer.create!(name: "Fox Racing", frame_maker: true)
Manufacturer.create!(name: "Fram", frame_maker: true)
Manufacturer.create!(name: "Freddie Grubb", frame_maker: true)
Manufacturer.create!(name: "Free Agent", frame_maker: true)
Manufacturer.create!(name: "Freedom", frame_maker: true)
Manufacturer.create!(name: "Freeload", frame_maker: true)
Manufacturer.create!(name: "FuelBelt", frame_maker: true)
Manufacturer.create!(name: "Fuji", frame_maker: true)
Manufacturer.create!(name: "Fulcrum", frame_maker: true)
Manufacturer.create!(name: "Fyxation", frame_maker: true)
Manufacturer.create!(name: "G Sport", frame_maker: true)
Manufacturer.create!(name: "G-Form", frame_maker: true)
Manufacturer.create!(name: "GT Bicycles", frame_maker: true)
Manufacturer.create!(name: "GU", frame_maker: true)
Manufacturer.create!(name: "Gamut", frame_maker: true)
Manufacturer.create!(name: "Gardin", frame_maker: true)
Manufacturer.create!(name: "Garmin", frame_maker: true)
Manufacturer.create!(name: "Gary Fisher", frame_maker: true)
Manufacturer.create!(name: "Gary Klein", frame_maker: true)
Manufacturer.create!(name: "Gates Carbon Drive", frame_maker: true)
Manufacturer.create!(name: "Gateway", frame_maker: true)
Manufacturer.create!(name: "Gazelle", frame_maker: true)
Manufacturer.create!(name: "Gear Aid", frame_maker: true)
Manufacturer.create!(name: "Gear Clamp", frame_maker: true)
Manufacturer.create!(name: "Gear Up", frame_maker: true)
Manufacturer.create!(name: "Geax", frame_maker: true)
Manufacturer.create!(name: "Gendron Bicycles", frame_maker: true)
Manufacturer.create!(name: "Genuine Innovations", frame_maker: true)
Manufacturer.create!(name: "Gepida", frame_maker: true)
Manufacturer.create!(name: "Giant", frame_maker: true)
Manufacturer.create!(name: "Gibbon Slacklines", frame_maker: true)
Manufacturer.create!(name: "Gitane", frame_maker: true)
Manufacturer.create!(name: "Glacier Glove", frame_maker: true)
Manufacturer.create!(name: "Gladiator Cycle Company", frame_maker: true)
Manufacturer.create!(name: "Globe", frame_maker: true)
Manufacturer.create!(name: "Gnome et Rhône", frame_maker: true)
Manufacturer.create!(name: "GoGirl", frame_maker: true)
Manufacturer.create!(name: "Gore", frame_maker: true)
Manufacturer.create!(name: "Gormully & Jeffery", frame_maker: true)
Manufacturer.create!(name: "Grab On", frame_maker: true)
Manufacturer.create!(name: "Grabber", frame_maker: true)
Manufacturer.create!(name: "Graber", frame_maker: true)
Manufacturer.create!(name: "Graflex", frame_maker: true)
Manufacturer.create!(name: "Granite Gear", frame_maker: true)
Manufacturer.create!(name: "Gravity", frame_maker: true)
Manufacturer.create!(name: "Greenfield", frame_maker: true)
Manufacturer.create!(name: "Greenspeed", frame_maker: true)
Manufacturer.create!(name: "Guerciotti", frame_maker: true)
Manufacturer.create!(name: "Gunnar", frame_maker: true)
Manufacturer.create!(name: "Guyot Designs", frame_maker: true)
Manufacturer.create!(name: "H Plus Son", frame_maker: true)
Manufacturer.create!(name: "HED", frame_maker: true)
Manufacturer.create!(name: "Halo", frame_maker: true)
Manufacturer.create!(name: "Hammer Nutrition", frame_maker: true)
Manufacturer.create!(name: "Handsome Cycles", frame_maker: true)
Manufacturer.create!(name: "Handspun", frame_maker: true)
Manufacturer.create!(name: "Haro", frame_maker: true)
Manufacturer.create!(name: "Harry Quinn", frame_maker: true)
Manufacturer.create!(name: "Harvey Cycle Works", frame_maker: true)
Manufacturer.create!(name: "Hase bikes", frame_maker: true)
Manufacturer.create!(name: "Hayes", frame_maker: true)
Manufacturer.create!(name: "Head", frame_maker: true)
Manufacturer.create!(name: "Headsweats", frame_maker: true)
Manufacturer.create!(name: "Heinkel", frame_maker: true)
Manufacturer.create!(name: "Helkama", frame_maker: true)
Manufacturer.create!(name: "Hercules Cycle and Motor Company company", frame_maker: true)
Manufacturer.create!(name: "Hercules Fahrrad GmbH & Co", frame_maker: true)
Manufacturer.create!(name: "Heritage", frame_maker: true)
Manufacturer.create!(name: "Hero Cycles Ltd", frame_maker: true)
Manufacturer.create!(name: "Hetchins", frame_maker: true)
Manufacturer.create!(name: "High Gear", frame_maker: true)
Manufacturer.create!(name: "Highland", frame_maker: true)
Manufacturer.create!(name: "Hillman", frame_maker: true)
Manufacturer.create!(name: "Hirzl", frame_maker: true)
Manufacturer.create!(name: "Hobson", frame_maker: true)
Manufacturer.create!(name: "Hoffman", frame_maker: true)
Manufacturer.create!(name: "Holdsworth", frame_maker: true)
Manufacturer.create!(name: "Honey Stinger", frame_maker: true)
Manufacturer.create!(name: "Hope", frame_maker: true)
Manufacturer.create!(name: "House of Talents", frame_maker: true)
Manufacturer.create!(name: "Hozan", frame_maker: true)
Manufacturer.create!(name: "HubBub", frame_maker: true)
Manufacturer.create!(name: "Hudz", frame_maker: true)
Manufacturer.create!(name: "Huffy", frame_maker: true)
Manufacturer.create!(name: "Humangear", frame_maker: true)
Manufacturer.create!(name: "Humber", frame_maker: true)
Manufacturer.create!(name: "Humble Frameworks", frame_maker: true)
Manufacturer.create!(name: "Hunter", frame_maker: true)
Manufacturer.create!(name: "Hurricane Components", frame_maker: true)
Manufacturer.create!(name: "Hurtu", frame_maker: true)
Manufacturer.create!(name: "Husqvarna Motorcycles", frame_maker: true)
Manufacturer.create!(name: "Hutchinson", frame_maker: true)
Manufacturer.create!(name: "Hyalite Equipment", frame_maker: true)
Manufacturer.create!(name: "Hydrapak", frame_maker: true)
Manufacturer.create!(name: "IBEX", frame_maker: true)
Manufacturer.create!(name: "IMBA", frame_maker: true)
Manufacturer.create!(name: "IRO Cycles", frame_maker: true)
Manufacturer.create!(name: "ISM", frame_maker: true)
Manufacturer.create!(name: "Ibis", frame_maker: true)
Manufacturer.create!(name: "Ice Trekkers", frame_maker: true)
Manufacturer.create!(name: "IceToolz", frame_maker: true)
Manufacturer.create!(name: "Ideal Bikes", frame_maker: true)
Manufacturer.create!(name: "Identiti", frame_maker: true)
Manufacturer.create!(name: "Incredibell", frame_maker: true)
Manufacturer.create!(name: "Independent Fabrication", frame_maker: true)
Manufacturer.create!(name: "Industrieverband Fahrzeugbau", frame_maker: true)
Manufacturer.create!(name: "Industry Nine", frame_maker: true)
Manufacturer.create!(name: "Infini", frame_maker: true)
Manufacturer.create!(name: "Innova", frame_maker: true)
Manufacturer.create!(name: "Intense", frame_maker: true)
Manufacturer.create!(name: "Iride Bicycles", frame_maker: true)
Manufacturer.create!(name: "Iron Horse Bicycles", frame_maker: true)
Manufacturer.create!(name: "Isla", frame_maker: true)
Manufacturer.create!(name: "Issimo Designs", frame_maker: true)
Manufacturer.create!(name: "Italvega", frame_maker: true)
Manufacturer.create!(name: "Itera plastic bicycle", frame_maker: true)
Manufacturer.create!(name: "Iver Johnson", frame_maker: true)
Manufacturer.create!(name: "Iverson", frame_maker: true)
Manufacturer.create!(name: "JMC Bicycles", frame_maker: true)
Manufacturer.create!(name: "JP Weigle's", frame_maker: true)
Manufacturer.create!(name: "Jagwire", frame_maker: true)
Manufacturer.create!(name: "Jamis", frame_maker: true)
Manufacturer.create!(name: "Jandd", frame_maker: true)
Manufacturer.create!(name: "Jelly Belly", frame_maker: true)
Manufacturer.create!(name: "JetBoil", frame_maker: true)
Manufacturer.create!(name: "Jittery Joe's", frame_maker: true)
Manufacturer.create!(name: "John Cherry bicycles", frame_maker: true)
Manufacturer.create!(name: "John Deere ", frame_maker: true)
Manufacturer.create!(name: "K-Edge", frame_maker: true)
Manufacturer.create!(name: "K2 Sports", frame_maker: true)
Manufacturer.create!(name: "KBC", frame_maker: true)
Manufacturer.create!(name: "KHS Bicycles", frame_maker: true)
Manufacturer.create!(name: "KMC", frame_maker: true)
Manufacturer.create!(name: "KS", frame_maker: true)
Manufacturer.create!(name: "KT Tape", frame_maker: true)
Manufacturer.create!(name: "KTM", frame_maker: true)
Manufacturer.create!(name: "KW Bicycle", frame_maker: true)
Manufacturer.create!(name: "Kalkhoff", frame_maker: true)
Manufacturer.create!(name: "Kalloy", frame_maker: true)
Manufacturer.create!(name: "Katadyn", frame_maker: true)
Manufacturer.create!(name: "Kazam", frame_maker: true)
Manufacturer.create!(name: "Keith Bontrager", frame_maker: true)
Manufacturer.create!(name: "Kenda", frame_maker: true)
Manufacturer.create!(name: "Kent International Inc", frame_maker: true)
Manufacturer.create!(name: "Kestrel USA", frame_maker: true)
Manufacturer.create!(name: "Kettler", frame_maker: true)
Manufacturer.create!(name: "Kia Motors", frame_maker: true)
Manufacturer.create!(name: "Kind Bar", frame_maker: true)
Manufacturer.create!(name: "Kinesis", frame_maker: true)
Manufacturer.create!(name: "Kinesis Industry", frame_maker: true)
Manufacturer.create!(name: "Kinetic", frame_maker: true)
Manufacturer.create!(name: "Kinetic Koffee", frame_maker: true)
Manufacturer.create!(name: "Kink", frame_maker: true)
Manufacturer.create!(name: "Kish Fabrication", frame_maker: true)
Manufacturer.create!(name: "Kiss My Face", frame_maker: true)
Manufacturer.create!(name: "Klean Kanteen", frame_maker: true)
Manufacturer.create!(name: "Klein Bikes", frame_maker: true)
Manufacturer.create!(name: "Knog", frame_maker: true)
Manufacturer.create!(name: "Koga-Miyata", frame_maker: true)
Manufacturer.create!(name: "Kogswell Cycles", frame_maker: true)
Manufacturer.create!(name: "Kona", frame_maker: true)
Manufacturer.create!(name: "Kool Kovers", frame_maker: true)
Manufacturer.create!(name: "Kool-Stop", frame_maker: true)
Manufacturer.create!(name: "Kreitler", frame_maker: true)
Manufacturer.create!(name: "Kronan", frame_maker: true)
Manufacturer.create!(name: "Kross SA", frame_maker: true)
Manufacturer.create!(name: "Kryptonite", frame_maker: true)
Manufacturer.create!(name: "Kuat", frame_maker: true)
Manufacturer.create!(name: "Kuota", frame_maker: true)
Manufacturer.create!(name: "Kuwahara", frame_maker: true)
Manufacturer.create!(name: "LOW//", frame_maker: true)
Manufacturer.create!(name: "Lapierre", frame_maker: true)
Manufacturer.create!(name: "Laurin & Klement", frame_maker: true)
Manufacturer.create!(name: "Lazer", frame_maker: true)
Manufacturer.create!(name: "LeMond Racing Cycles", frame_maker: true)
Manufacturer.create!(name: "Leader Bikes", frame_maker: true)
Manufacturer.create!(name: "Leg Lube", frame_maker: true)
Manufacturer.create!(name: "Legacy Frameworks", frame_maker: true)
Manufacturer.create!(name: "Lezyne", frame_maker: true)
Manufacturer.create!(name: "Light My Fire", frame_maker: true)
Manufacturer.create!(name: "Light and Motion", frame_maker: true)
Manufacturer.create!(name: "Lightning Cycle Dynamics", frame_maker: true)
Manufacturer.create!(name: "Linus", frame_maker: true)
Manufacturer.create!(name: "Litespeed", frame_maker: true)
Manufacturer.create!(name: "Lizard Skins", frame_maker: true)
Manufacturer.create!(name: "Loctite", frame_maker: true)
Manufacturer.create!(name: "Loekie", frame_maker: true)
Manufacturer.create!(name: "Loekie ", frame_maker: true)
Manufacturer.create!(name: "Lonely Planet", frame_maker: true)
Manufacturer.create!(name: "Look", frame_maker: true)
Manufacturer.create!(name: "Lotus", frame_maker: true)
Manufacturer.create!(name: "Louis Garneau", frame_maker: true)
Manufacturer.create!(name: "Louison Bobet", frame_maker: true)
Manufacturer.create!(name: "Lycoming Engines", frame_maker: true)
Manufacturer.create!(name: "Lynskey", frame_maker: true)
Manufacturer.create!(name: "M Essentials", frame_maker: true)
Manufacturer.create!(name: "MKS", frame_maker: true)
Manufacturer.create!(name: "MRP", frame_maker: true)
Manufacturer.create!(name: "MSR", frame_maker: true)
Manufacturer.create!(name: "MTI Adventurewear", frame_maker: true)
Manufacturer.create!(name: "Magellan", frame_maker: true)
Manufacturer.create!(name: "Magna", frame_maker: true)
Manufacturer.create!(name: "Malvern Star", frame_maker: true)
Manufacturer.create!(name: "ManKind", frame_maker: true)
Manufacturer.create!(name: "Manhattan", frame_maker: true)
Manufacturer.create!(name: "Manitou", frame_maker: true)
Manufacturer.create!(name: "Maraton", frame_maker: true)
Manufacturer.create!(name: "Marin Bikes", frame_maker: true)
Manufacturer.create!(name: "Marson", frame_maker: true)
Manufacturer.create!(name: "Maruishi", frame_maker: true)
Manufacturer.create!(name: "Marzocchi", frame_maker: true)
Manufacturer.create!(name: "Masi", frame_maker: true)
Manufacturer.create!(name: "Master Lock", frame_maker: true)
Manufacturer.create!(name: "Matchless", frame_maker: true)
Manufacturer.create!(name: "Matra", frame_maker: true)
Manufacturer.create!(name: "Mavic", frame_maker: true)
Manufacturer.create!(name: "Maxit", frame_maker: true)
Manufacturer.create!(name: "Maxxis", frame_maker: true)
Manufacturer.create!(name: "Mechanical Threads", frame_maker: true)
Manufacturer.create!(name: "Meiser", frame_maker: true)
Manufacturer.create!(name: "Melon Bicycles", frame_maker: true)
Manufacturer.create!(name: "Mercian Cycles", frame_maker: true)
Manufacturer.create!(name: "Mercier", frame_maker: true)
Manufacturer.create!(name: "Merida Bikes", frame_maker: true)
Manufacturer.create!(name: "Merlin", frame_maker: true)
Manufacturer.create!(name: "Merrell", frame_maker: true)
Manufacturer.create!(name: "MetaBikes", frame_maker: true)
Manufacturer.create!(name: "Metric Hardware", frame_maker: true)
Manufacturer.create!(name: "Micajah C. Henley", frame_maker: true)
Manufacturer.create!(name: "Miche", frame_maker: true)
Manufacturer.create!(name: "Michelin", frame_maker: true)
Manufacturer.create!(name: "MicroShift", frame_maker: true)
Manufacturer.create!(name: "Miele bicycles", frame_maker: true)
Manufacturer.create!(name: "Milwaukee Bicycle Co.", frame_maker: true)
Manufacturer.create!(name: "Minoura", frame_maker: true)
Manufacturer.create!(name: "MirraCo ", frame_maker: true)
Manufacturer.create!(name: "Mirrycle", frame_maker: true)
Manufacturer.create!(name: "Mission Bicycles", frame_maker: true)
Manufacturer.create!(name: "Miyata", frame_maker: true)
Manufacturer.create!(name: "Monark", frame_maker: true)
Manufacturer.create!(name: "Mondia", frame_maker: true)
Manufacturer.create!(name: "Mongoose", frame_maker: true)
Manufacturer.create!(name: "Montague", frame_maker: true)
Manufacturer.create!(name: "Montague Bicycles", frame_maker: true)
Manufacturer.create!(name: "Moots Cycles", frame_maker: true)
Manufacturer.create!(name: "Mophie", frame_maker: true)
Manufacturer.create!(name: "Moser Cicli", frame_maker: true)
Manufacturer.create!(name: "Motiv", frame_maker: true)
Manufacturer.create!(name: "Motobecane", frame_maker: true)
Manufacturer.create!(name: "Moulden", frame_maker: true)
Manufacturer.create!(name: "Moulton Bicycle", frame_maker: true)
Manufacturer.create!(name: "Mountainsmith", frame_maker: true)
Manufacturer.create!(name: "Mr. Tuffy", frame_maker: true)
Manufacturer.create!(name: "Muddy Fox", frame_maker: true)
Manufacturer.create!(name: "Murray", frame_maker: true)
Manufacturer.create!(name: "Mutant Bikes", frame_maker: true)
Manufacturer.create!(name: "Mutiny", frame_maker: true)
Manufacturer.create!(name: "N Gear", frame_maker: true)
Manufacturer.create!(name: "NEMO", frame_maker: true)
Manufacturer.create!(name: "NS Bikes", frame_maker: true)
Manufacturer.create!(name: "NSU Motorenwerke", frame_maker: true)
Manufacturer.create!(name: "Nalgene", frame_maker: true)
Manufacturer.create!(name: "Nantucket Bike Basket Company", frame_maker: true)
Manufacturer.create!(name: "Nashbar", frame_maker: true)
Manufacturer.create!(name: "Nathan", frame_maker: true)
Manufacturer.create!(name: "National", frame_maker: true)
Manufacturer.create!(name: "Native", frame_maker: true)
Manufacturer.create!(name: "Neil Pryde", frame_maker: true)
Manufacturer.create!(name: "Nema", frame_maker: true)
Manufacturer.create!(name: "Neobike", frame_maker: true)
Manufacturer.create!(name: "New Albion", frame_maker: true)
Manufacturer.create!(name: "New Balance", frame_maker: true)
Manufacturer.create!(name: "Next", frame_maker: true)
Manufacturer.create!(name: "Niner", frame_maker: true)
Manufacturer.create!(name: "Nishiki", frame_maker: true)
Manufacturer.create!(name: "Nite Ize", frame_maker: true)
Manufacturer.create!(name: "NiteRider", frame_maker: true)
Manufacturer.create!(name: "Nitto", frame_maker: true)
Manufacturer.create!(name: "Nokon", frame_maker: true)
Manufacturer.create!(name: "Norco Performance Bikes", frame_maker: true)
Manufacturer.create!(name: "Norman Cycles", frame_maker: true)
Manufacturer.create!(name: "North Shore Billet", frame_maker: true)
Manufacturer.create!(name: "Northrock", frame_maker: true)
Manufacturer.create!(name: "Novara", frame_maker: true)
Manufacturer.create!(name: "NuVinci", frame_maker: true)
Manufacturer.create!(name: "Nymanbolagen", frame_maker: true)
Manufacturer.create!(name: "O-Stand", frame_maker: true)
Manufacturer.create!(name: "O2", frame_maker: true)
Manufacturer.create!(name: "ODI", frame_maker: true)
Manufacturer.create!(name: "Odyssey", frame_maker: true)
Manufacturer.create!(name: "Ohio Travel Bag", frame_maker: true)
Manufacturer.create!(name: "OnGuard", frame_maker: true)
Manufacturer.create!(name: "One Way", frame_maker: true)
Manufacturer.create!(name: "Opel", frame_maker: true)
Manufacturer.create!(name: "Optic Nerve", frame_maker: true)
Manufacturer.create!(name: "Optimus", frame_maker: true)
Manufacturer.create!(name: "Opus", frame_maker: true)
Manufacturer.create!(name: "Orange", frame_maker: true)
Manufacturer.create!(name: "Orange Seal", frame_maker: true)
Manufacturer.create!(name: "Orbea", frame_maker: true)
Manufacturer.create!(name: "Orbit", frame_maker: true)
Manufacturer.create!(name: "Orient Bikes", frame_maker: true)
Manufacturer.create!(name: "Origin-8", frame_maker: true)
Manufacturer.create!(name: "Ortlieb", frame_maker: true)
Manufacturer.create!(name: "Other", frame_maker: true)
Manufacturer.create!(name: "Oury", frame_maker: true)
Manufacturer.create!(name: "OutGo", frame_maker: true)
Manufacturer.create!(name: "Owl 360", frame_maker: true)
Manufacturer.create!(name: "Oyama", frame_maker: true)
Manufacturer.create!(name: "Ozone", frame_maker: true)
Manufacturer.create!(name: "PDW", frame_maker: true)
Manufacturer.create!(name: "POC", frame_maker: true)
Manufacturer.create!(name: "Pace Sportswear", frame_maker: true)
Manufacturer.create!(name: "Paceline Products", frame_maker: true)
Manufacturer.create!(name: "Pacific Cycle", frame_maker: true)
Manufacturer.create!(name: "PackTowl", frame_maker: true)
Manufacturer.create!(name: "Pake", frame_maker: true)
Manufacturer.create!(name: "Panaracer", frame_maker: true)
Manufacturer.create!(name: "Panasonic", frame_maker: true)
Manufacturer.create!(name: "Park", frame_maker: true)
Manufacturer.create!(name: "Parkpre", frame_maker: true)
Manufacturer.create!(name: "Parlee", frame_maker: true)
Manufacturer.create!(name: "Parlee Cycles", frame_maker: true)
Manufacturer.create!(name: "Pashley Cycles", frame_maker: true)
Manufacturer.create!(name: "Patria", frame_maker: true)
Manufacturer.create!(name: "Paul Component Engineering", frame_maker: true)
Manufacturer.create!(name: "Pearl Izumi", frame_maker: true)
Manufacturer.create!(name: "Pedco", frame_maker: true)
Manufacturer.create!(name: "Pedersen bicycle", frame_maker: true)
Manufacturer.create!(name: "Pedro's", frame_maker: true)
Manufacturer.create!(name: "Penguin Brands", frame_maker: true)
Manufacturer.create!(name: "Performance", frame_maker: true)
Manufacturer.create!(name: "Peugeot", frame_maker: true)
Manufacturer.create!(name: "Phat Cycles", frame_maker: true)
Manufacturer.create!(name: "Phil Wood", frame_maker: true)
Manufacturer.create!(name: "Philips", frame_maker: true)
Manufacturer.create!(name: "Phillips Cycles", frame_maker: true)
Manufacturer.create!(name: "Phoenix", frame_maker: true)
Manufacturer.create!(name: "Phorm", frame_maker: true)
Manufacturer.create!(name: "Pierce-Arrow", frame_maker: true)
Manufacturer.create!(name: "Pinarello", frame_maker: true)
Manufacturer.create!(name: "Pinhead", frame_maker: true)
Manufacturer.create!(name: "Pitlock", frame_maker: true)
Manufacturer.create!(name: "Pivot", frame_maker: true)
Manufacturer.create!(name: "Planet Bike", frame_maker: true)
Manufacturer.create!(name: "Planet X", frame_maker: true)
Manufacturer.create!(name: "Platypus", frame_maker: true)
Manufacturer.create!(name: "Pletscher", frame_maker: true)
Manufacturer.create!(name: "Po Campo", frame_maker: true)
Manufacturer.create!(name: "Pocket Bicycles", frame_maker: true)
Manufacturer.create!(name: "Pogliaghi", frame_maker: true)
Manufacturer.create!(name: "Polar", frame_maker: true)
Manufacturer.create!(name: "Polar Bottles", frame_maker: true)
Manufacturer.create!(name: "Polygon", frame_maker: true)
Manufacturer.create!(name: "Pope Manufacturing Company", frame_maker: true)
Manufacturer.create!(name: "Power Grips", frame_maker: true)
Manufacturer.create!(name: "PowerBar", frame_maker: true)
Manufacturer.create!(name: "PowerTap", frame_maker: true)
Manufacturer.create!(name: "Premier Motorcycles", frame_maker: true)
Manufacturer.create!(name: "Primal Wear", frame_maker: true)
Manufacturer.create!(name: "Primo", frame_maker: true)
Manufacturer.create!(name: "Princeton Tec", frame_maker: true)
Manufacturer.create!(name: "Principia", frame_maker: true)
Manufacturer.create!(name: "Private label", frame_maker: true)
Manufacturer.create!(name: "Pro-tec", frame_maker: true)
Manufacturer.create!(name: "ProBar", frame_maker: true)
Manufacturer.create!(name: "ProGold", frame_maker: true)
Manufacturer.create!(name: "Problem Solvers", frame_maker: true)
Manufacturer.create!(name: "Procycle Group", frame_maker: true)
Manufacturer.create!(name: "Profile Design", frame_maker: true)
Manufacturer.create!(name: "Profile Racing", frame_maker: true)
Manufacturer.create!(name: "Prologo", frame_maker: true)
Manufacturer.create!(name: "Promax", frame_maker: true)
Manufacturer.create!(name: "Prophete", frame_maker: true)
Manufacturer.create!(name: "Public", frame_maker: true)
Manufacturer.create!(name: "Puch", frame_maker: true)
Manufacturer.create!(name: "Pure Fix", frame_maker: true)
Manufacturer.create!(name: "Python", frame_maker: true)
Manufacturer.create!(name: "Q-Outdoor", frame_maker: true)
Manufacturer.create!(name: "Q-Tubes", frame_maker: true)
Manufacturer.create!(name: "QBP", frame_maker: true)
Manufacturer.create!(name: "QBP Kits", frame_maker: true)
Manufacturer.create!(name: "Quadrant Cycle Company", frame_maker: true)
Manufacturer.create!(name: "Quest", frame_maker: true)
Manufacturer.create!(name: "Quik Stik", frame_maker: true)
Manufacturer.create!(name: "Quintana Roo", frame_maker: true)
Manufacturer.create!(name: "R12", frame_maker: true)
Manufacturer.create!(name: "RIH", frame_maker: true)
Manufacturer.create!(name: "RPM", frame_maker: true)
Manufacturer.create!(name: "RRB (Rat Rod Bikes)", frame_maker: true)
Manufacturer.create!(name: "RST", frame_maker: true)
Manufacturer.create!(name: "RaceFace", frame_maker: true)
Manufacturer.create!(name: "Racktime", frame_maker: true)
Manufacturer.create!(name: "Radio Flyer", frame_maker: true)
Manufacturer.create!(name: "Raleigh", frame_maker: true)
Manufacturer.create!(name: "Ram", frame_maker: true)
Manufacturer.create!(name: "Rambler", frame_maker: true)
Manufacturer.create!(name: "Rans Designs", frame_maker: true)
Manufacturer.create!(name: "Rawland Cycles", frame_maker: true)
Manufacturer.create!(name: "Razor USA", frame_maker: true)
Manufacturer.create!(name: "ReTale", frame_maker: true)
Manufacturer.create!(name: "Redline", frame_maker: true)
Manufacturer.create!(name: "Redlof", frame_maker: true)
Manufacturer.create!(name: "Reflect Sports", frame_maker: true)
Manufacturer.create!(name: "Regina", frame_maker: true)
Manufacturer.create!(name: "Rema", frame_maker: true)
Manufacturer.create!(name: "Renthal", frame_maker: true)
Manufacturer.create!(name: "René Herse", frame_maker: true)
Manufacturer.create!(name: "Republic", frame_maker: true)
Manufacturer.create!(name: "Republic of China", frame_maker: true)
Manufacturer.create!(name: "Resist", frame_maker: true)
Manufacturer.create!(name: "Revelate Designs", frame_maker: true)
Manufacturer.create!(name: "Rhythm", frame_maker: true)
Manufacturer.create!(name: "Ribble", frame_maker: true)
Manufacturer.create!(name: "Ride2", frame_maker: true)
Manufacturer.create!(name: "Ridgeback", frame_maker: true)
Manufacturer.create!(name: "Ridley", frame_maker: true)
Manufacturer.create!(name: "Riese und Müller", frame_maker: true)
Manufacturer.create!(name: "Ritchey", frame_maker: true)
Manufacturer.create!(name: "Ritte", frame_maker: true)
Manufacturer.create!(name: "Rivendell Bicycle Works", frame_maker: true)
Manufacturer.create!(name: "Roadmaster", frame_maker: true)
Manufacturer.create!(name: "Roberts Cycles", frame_maker: true)
Manufacturer.create!(name: "Robin Hood", frame_maker: true)
Manufacturer.create!(name: "Rock-N-Roll", frame_maker: true)
Manufacturer.create!(name: "RockShox", frame_maker: true)
Manufacturer.create!(name: "Rocky Mountain Bicycles", frame_maker: true)
Manufacturer.create!(name: "Rocky Mounts", frame_maker: true)
Manufacturer.create!(name: "Rohloff", frame_maker: true)
Manufacturer.create!(name: "Rokform", frame_maker: true)
Manufacturer.create!(name: "Rola", frame_maker: true)
Manufacturer.create!(name: "Ross", frame_maker: true)
Manufacturer.create!(name: "Rossignol", frame_maker: true)
Manufacturer.create!(name: "Rossin", frame_maker: true)
Manufacturer.create!(name: "Rover Company", frame_maker: true)
Manufacturer.create!(name: "Rowbike", frame_maker: true)
Manufacturer.create!(name: "Rox", frame_maker: true)
Manufacturer.create!(name: "Royal", frame_maker: true)
Manufacturer.create!(name: "Royce Union ", frame_maker: true)
Manufacturer.create!(name: "Rudge-Whitworth", frame_maker: true)
Manufacturer.create!(name: "S and S", frame_maker: true)
Manufacturer.create!(name: "S&M Bikes", frame_maker: true)
Manufacturer.create!(name: "SCOTT Sports", frame_maker: true)
Manufacturer.create!(name: "SDG", frame_maker: true)
Manufacturer.create!(name: "SE Bikes", frame_maker: true)
Manufacturer.create!(name: "SKS", frame_maker: true)
Manufacturer.create!(name: "SLS3", frame_maker: true)
Manufacturer.create!(name: "SR Suntour", frame_maker: true)
Manufacturer.create!(name: "SRAM", frame_maker: true)
Manufacturer.create!(name: "SST", frame_maker: true)
Manufacturer.create!(name: "START", frame_maker: true)
Manufacturer.create!(name: "SWEAT GUTR", frame_maker: true)
Manufacturer.create!(name: "Salomon", frame_maker: true)
Manufacturer.create!(name: "Salsa", frame_maker: true)
Manufacturer.create!(name: "SaltStick", frame_maker: true)
Manufacturer.create!(name: "Samchuly", frame_maker: true)
Manufacturer.create!(name: "Sanderson", frame_maker: true)
Manufacturer.create!(name: "Santa Cruz", frame_maker: true)
Manufacturer.create!(name: "Santana Cycles", frame_maker: true)
Manufacturer.create!(name: "Saracen Cycles", frame_maker: true)
Manufacturer.create!(name: "Saris", frame_maker: true)
Manufacturer.create!(name: "Scania AB", frame_maker: true)
Manufacturer.create!(name: "Scattante", frame_maker: true)
Manufacturer.create!(name: "Schwalbe", frame_maker: true)
Manufacturer.create!(name: "Schwinn", frame_maker: true)
Manufacturer.create!(name: "Scotty", frame_maker: true)
Manufacturer.create!(name: "Seal Line", frame_maker: true)
Manufacturer.create!(name: "Sears Roebuck", frame_maker: true)
Manufacturer.create!(name: "Season", frame_maker: true)
Manufacturer.create!(name: "Seattle Sports Company", frame_maker: true)
Manufacturer.create!(name: "Sekine", frame_maker: true)
Manufacturer.create!(name: "Selle Italia", frame_maker: true)
Manufacturer.create!(name: "Selle Royal", frame_maker: true)
Manufacturer.create!(name: "Selle San Marco", frame_maker: true)
Manufacturer.create!(name: "Serotta", frame_maker: true)
Manufacturer.create!(name: "Seven Cycles", frame_maker: true)
Manufacturer.create!(name: "Shadow Conspiracy", frame_maker: true)
Manufacturer.create!(name: "Shelby Cycle Company", frame_maker: true)
Manufacturer.create!(name: "Sherpani", frame_maker: true)
Manufacturer.create!(name: "Shimano", frame_maker: true)
Manufacturer.create!(name: "Shinola", frame_maker: true)
Manufacturer.create!(name: "Shogun", frame_maker: true)
Manufacturer.create!(name: "Shredder", frame_maker: true)
Manufacturer.create!(name: "Sidi", frame_maker: true)
Manufacturer.create!(name: "Sierra Designs", frame_maker: true)
Manufacturer.create!(name: "Sigma", frame_maker: true)
Manufacturer.create!(name: "Silca", frame_maker: true)
Manufacturer.create!(name: "Simple Green", frame_maker: true)
Manufacturer.create!(name: "Simson", frame_maker: true)
Manufacturer.create!(name: "Sinclair Research", frame_maker: true)
Manufacturer.create!(name: "Singletrack Solutions", frame_maker: true)
Manufacturer.create!(name: "Sinz", frame_maker: true)
Manufacturer.create!(name: "SixSixOne", frame_maker: true)
Manufacturer.create!(name: "Skadi", frame_maker: true)
Manufacturer.create!(name: "Skinz", frame_maker: true)
Manufacturer.create!(name: "Skratch Labs", frame_maker: true)
Manufacturer.create!(name: "Skyway ", frame_maker: true)
Manufacturer.create!(name: "Slime", frame_maker: true)
Manufacturer.create!(name: "Smartwool", frame_maker: true)
Manufacturer.create!(name: "SockGuy", frame_maker: true)
Manufacturer.create!(name: "Sohrab Cycles", frame_maker: true)
Manufacturer.create!(name: "Sole", frame_maker: true)
Manufacturer.create!(name: "Solex", frame_maker: true)
Manufacturer.create!(name: "Solio", frame_maker: true)
Manufacturer.create!(name: "Solé Bicycle Co.", frame_maker: true)
Manufacturer.create!(name: "Soma", frame_maker: true)
Manufacturer.create!(name: "Somec", frame_maker: true)
Manufacturer.create!(name: "Source", frame_maker: true)
Manufacturer.create!(name: "Spalding Bicycles", frame_maker: true)
Manufacturer.create!(name: "Sparta B.V.", frame_maker: true)
Manufacturer.create!(name: "Specialized", frame_maker: true)
Manufacturer.create!(name: "Spectro Oil", frame_maker: true)
Manufacturer.create!(name: "Speedfil", frame_maker: true)
Manufacturer.create!(name: "Speedwell bicycles", frame_maker: true)
Manufacturer.create!(name: "Spenco", frame_maker: true)
Manufacturer.create!(name: "SpiderTech", frame_maker: true)
Manufacturer.create!(name: "Spike", frame_maker: true)
Manufacturer.create!(name: "Spinskins", frame_maker: true)
Manufacturer.create!(name: "Spooky", frame_maker: true)
Manufacturer.create!(name: "SportRack", frame_maker: true)
Manufacturer.create!(name: "Sportlegs", frame_maker: true)
Manufacturer.create!(name: "Sportourer", frame_maker: true)
Manufacturer.create!(name: "Spot", frame_maker: true)
Manufacturer.create!(name: "Sprintech", frame_maker: true)
Manufacturer.create!(name: "Squeal Out", frame_maker: true)
Manufacturer.create!(name: "Squire", frame_maker: true)
Manufacturer.create!(name: "St. Tropez", frame_maker: true)
Manufacturer.create!(name: "Staiger", frame_maker: true)
Manufacturer.create!(name: "Stan's No Tubes", frame_maker: true)
Manufacturer.create!(name: "Stanley", frame_maker: true)
Manufacturer.create!(name: "Star Motor Company", frame_maker: true)
Manufacturer.create!(name: "State Bicycle Co.", frame_maker: true)
Manufacturer.create!(name: "Steadyrack", frame_maker: true)
Manufacturer.create!(name: "Stein", frame_maker: true)
Manufacturer.create!(name: "Stein Trikes", frame_maker: true)
Manufacturer.create!(name: "Stelber Cycle Corp", frame_maker: true)
Manufacturer.create!(name: "Stella", frame_maker: true)
Manufacturer.create!(name: "Stem CAPtain", frame_maker: true)
Manufacturer.create!(name: "Sterling Bicycle Co.", frame_maker: true)
Manufacturer.create!(name: "Steve Potts", frame_maker: true)
Manufacturer.create!(name: "Stevens", frame_maker: true)
Manufacturer.create!(name: "Stoemper", frame_maker: true)
Manufacturer.create!(name: "Stolen Bicycle Co.", frame_maker: true)
Manufacturer.create!(name: "Stolen Bikes", frame_maker: true)
Manufacturer.create!(name: "Stolen Parts", frame_maker: true)
Manufacturer.create!(name: "Stop Flats 2", frame_maker: true)
Manufacturer.create!(name: "Strada Customs", frame_maker: true)
Manufacturer.create!(name: "Straitline", frame_maker: true)
Manufacturer.create!(name: "Strida", frame_maker: true)
Manufacturer.create!(name: "Strider Sports", frame_maker: true)
Manufacturer.create!(name: "Sturmey-Archer", frame_maker: true)
Manufacturer.create!(name: "Stålhästen", frame_maker: true)
Manufacturer.create!(name: "Subrosa", frame_maker: true)
Manufacturer.create!(name: "Suelo", frame_maker: true)
Manufacturer.create!(name: "Sugino", frame_maker: true)
Manufacturer.create!(name: "Sun", frame_maker: true)
Manufacturer.create!(name: "Sun Ringle", frame_maker: true)
Manufacturer.create!(name: "SunRace", frame_maker: true)
Manufacturer.create!(name: "Sunday", frame_maker: true)
Manufacturer.create!(name: "Sunn", frame_maker: true)
Manufacturer.create!(name: "Suomi", frame_maker: true)
Manufacturer.create!(name: "Superfeet", frame_maker: true)
Manufacturer.create!(name: "Supernova", frame_maker: true)
Manufacturer.create!(name: "Surly", frame_maker: true)
Manufacturer.create!(name: "Sutherlands", frame_maker: true)
Manufacturer.create!(name: "Suunto", frame_maker: true)
Manufacturer.create!(name: "Suzuki", frame_maker: true)
Manufacturer.create!(name: "Swix", frame_maker: true)
Manufacturer.create!(name: "Swobo", frame_maker: true)
Manufacturer.create!(name: "Syntace", frame_maker: true)
Manufacturer.create!(name: "T Mat Pro", frame_maker: true)
Manufacturer.create!(name: "TH Industries", frame_maker: true)
Manufacturer.create!(name: "TI Cycles of India", frame_maker: true)
Manufacturer.create!(name: "TRP", frame_maker: true)
Manufacturer.create!(name: "TYR", frame_maker: true)
Manufacturer.create!(name: "Tacx", frame_maker: true)
Manufacturer.create!(name: "Takara", frame_maker: true)
Manufacturer.create!(name: "Talisman", frame_maker: true)
Manufacturer.create!(name: "Tamer", frame_maker: true)
Manufacturer.create!(name: "Tange-Seiki", frame_maker: true)
Manufacturer.create!(name: "Tangent Products", frame_maker: true)
Manufacturer.create!(name: "Tec Labs", frame_maker: true)
Manufacturer.create!(name: "Tektro", frame_maker: true)
Manufacturer.create!(name: "Tern", frame_maker: true)
Manufacturer.create!(name: "Terrot", frame_maker: true)
Manufacturer.create!(name: "Terry", frame_maker: true)
Manufacturer.create!(name: "The Arthur Pequegnat Clock Company clock-company", frame_maker: true)
Manufacturer.create!(name: "The Bicycle Forge", frame_maker: true)
Manufacturer.create!(name: "The Hive", frame_maker: true)
Manufacturer.create!(name: "Thinksport", frame_maker: true)
Manufacturer.create!(name: "Thomas Motor Company", frame_maker: true)
Manufacturer.create!(name: "Thomson", frame_maker: true)
Manufacturer.create!(name: "Thorn Cycles", frame_maker: true)
Manufacturer.create!(name: "Thule", frame_maker: true)
Manufacturer.create!(name: "Ti Cycles", frame_maker: true)
Manufacturer.create!(name: "Tigr", frame_maker: true)
Manufacturer.create!(name: "Timbuk2", frame_maker: true)
Manufacturer.create!(name: "Time", frame_maker: true)
Manufacturer.create!(name: "Timex", frame_maker: true)
Manufacturer.create!(name: "Tioga", frame_maker: true)
Manufacturer.create!(name: "Titan", frame_maker: true)
Manufacturer.create!(name: "Titus", frame_maker: true)
Manufacturer.create!(name: "Toko", frame_maker: true)
Manufacturer.create!(name: "Tommaso", frame_maker: true)
Manufacturer.create!(name: "Topeak", frame_maker: true)
Manufacturer.create!(name: "TorHans", frame_maker: true)
Manufacturer.create!(name: "Torker", frame_maker: true)
Manufacturer.create!(name: "Transition Bikes", frame_maker: true)
Manufacturer.create!(name: "Tranz-X", frame_maker: true)
Manufacturer.create!(name: "Tree", frame_maker: true)
Manufacturer.create!(name: "Trek", frame_maker: true)
Manufacturer.create!(name: "Tressostar", frame_maker: true)
Manufacturer.create!(name: "TriFlow", frame_maker: true)
Manufacturer.create!(name: "TriSlide", frame_maker: true)
Manufacturer.create!(name: "TriSwim", frame_maker: true)
Manufacturer.create!(name: "Trigger Point", frame_maker: true)
Manufacturer.create!(name: "Trik Topz", frame_maker: true)
Manufacturer.create!(name: "Triumph Cycle", frame_maker: true)
Manufacturer.create!(name: "TruVativ", frame_maker: true)
Manufacturer.create!(name: "Tubasti", frame_maker: true)
Manufacturer.create!(name: "Tufo", frame_maker: true)
Manufacturer.create!(name: "Tunturi", frame_maker: true)
Manufacturer.create!(name: "Turner Suspension Bicycles", frame_maker: true)
Manufacturer.create!(name: "Twin Six", frame_maker: true)
Manufacturer.create!(name: "TwoFish", frame_maker: true)
Manufacturer.create!(name: "UCLEAR", frame_maker: true)
Manufacturer.create!(name: "UCO", frame_maker: true)
Manufacturer.create!(name: "Uline", frame_maker: true)
Manufacturer.create!(name: "Ultimate Survival Technologies technologies", frame_maker: true)
Manufacturer.create!(name: "UltraPaws", frame_maker: true)
Manufacturer.create!(name: "Umberto Dei", frame_maker: true)
Manufacturer.create!(name: "Unior", frame_maker: true)
Manufacturer.create!(name: "Univega", frame_maker: true)
Manufacturer.create!(name: "Unknown", frame_maker: true)
Manufacturer.create!(name: "Unknown manufacturer", frame_maker: true)
Manufacturer.create!(name: "Urago", frame_maker: true)
Manufacturer.create!(name: "Utopia", frame_maker: true)
Manufacturer.create!(name: "VP Components", frame_maker: true)
Manufacturer.create!(name: "Valdora", frame_maker: true)
Manufacturer.create!(name: "Van Herwerden", frame_maker: true)
Manufacturer.create!(name: "Vargo", frame_maker: true)
Manufacturer.create!(name: "Various Manufacturers", frame_maker: true)
Manufacturer.create!(name: "Vassago", frame_maker: true)
Manufacturer.create!(name: "Vee Rubber", frame_maker: true)
Manufacturer.create!(name: "Velo", frame_maker: true)
Manufacturer.create!(name: "Velo Orange", frame_maker: true)
Manufacturer.create!(name: "Velo Press", frame_maker: true)
Manufacturer.create!(name: "Velo Vie", frame_maker: true)
Manufacturer.create!(name: "Velocity", frame_maker: true)
Manufacturer.create!(name: "Velomotors", frame_maker: true)
Manufacturer.create!(name: "Velorbis", frame_maker: true)
Manufacturer.create!(name: "Velox", frame_maker: true)
Manufacturer.create!(name: "Verde", frame_maker: true)
Manufacturer.create!(name: "Versa", frame_maker: true)
Manufacturer.create!(name: "Vilano", frame_maker: true)
Manufacturer.create!(name: "Villy Customs", frame_maker: true)
Manufacturer.create!(name: "Vincero Design", frame_maker: true)
Manufacturer.create!(name: "Vindec High Riser", frame_maker: true)
Manufacturer.create!(name: "Virtue", frame_maker: true)
Manufacturer.create!(name: "Viscount", frame_maker: true)
Manufacturer.create!(name: "Vision", frame_maker: true)
Manufacturer.create!(name: "Vittoria", frame_maker: true)
Manufacturer.create!(name: "Vitus", frame_maker: true)
Manufacturer.create!(name: "Volagi", frame_maker: true)
Manufacturer.create!(name: "Volume", frame_maker: true)
Manufacturer.create!(name: "Volume Bikes", frame_maker: true)
Manufacturer.create!(name: "Voodoo", frame_maker: true)
Manufacturer.create!(name: "Vortrieb", frame_maker: true)
Manufacturer.create!(name: "VéloSoleX", frame_maker: true)
Manufacturer.create!(name: "WD-40 Bike", frame_maker: true)
Manufacturer.create!(name: "WTB", frame_maker: true)
Manufacturer.create!(name: "Wabi Cycles", frame_maker: true)
Manufacturer.create!(name: "Wahoo Fitness", frame_maker: true)
Manufacturer.create!(name: "Wald", frame_maker: true)
Manufacturer.create!(name: "Walking Bird", frame_maker: true)
Manufacturer.create!(name: "Waterford Precision Cycles", frame_maker: true)
Manufacturer.create!(name: "WeThePeople", frame_maker: true)
Manufacturer.create!(name: "WeeRide", frame_maker: true)
Manufacturer.create!(name: "Wellgo", frame_maker: true)
Manufacturer.create!(name: "Wheels Manufacturing", frame_maker: true)
Manufacturer.create!(name: "Wheelsmith", frame_maker: true)
Manufacturer.create!(name: "Where to Bike", frame_maker: true)
Manufacturer.create!(name: "Whisky Parts Co", frame_maker: true)
Manufacturer.create!(name: "Whispbar", frame_maker: true)
Manufacturer.create!(name: "White Bros", frame_maker: true)
Manufacturer.create!(name: "White Lightning", frame_maker: true)
Manufacturer.create!(name: "Wigwam", frame_maker: true)
Manufacturer.create!(name: "Wilderness Trail Bikes", frame_maker: true)
Manufacturer.create!(name: "Wilier Triestina", frame_maker: true)
Manufacturer.create!(name: "Williams", frame_maker: true)
Manufacturer.create!(name: "Willworx", frame_maker: true)
Manufacturer.create!(name: "Win", frame_maker: true)
Manufacturer.create!(name: "Windsor", frame_maker: true)
Manufacturer.create!(name: "Winora", frame_maker: true)
Manufacturer.create!(name: "Winter Bicycles", frame_maker: true)
Manufacturer.create!(name: "Wippermann", frame_maker: true)
Manufacturer.create!(name: "Witcomb Cycles", frame_maker: true)
Manufacturer.create!(name: "Witz", frame_maker: true)
Manufacturer.create!(name: "Wooden Bike Coffee", frame_maker: true)
Manufacturer.create!(name: "WorkCycles", frame_maker: true)
Manufacturer.create!(name: "Worksman Cycles", frame_maker: true)
Manufacturer.create!(name: "World Bicycle Relief", frame_maker: true)
Manufacturer.create!(name: "World Jerseys", frame_maker: true)
Manufacturer.create!(name: "Wright Cycle Company", frame_maker: true)
Manufacturer.create!(name: "X-Fusion", frame_maker: true)
Manufacturer.create!(name: "X-Lab", frame_maker: true)
Manufacturer.create!(name: "X-Treme", frame_maker: true)
Manufacturer.create!(name: "Xootr", frame_maker: true)
Manufacturer.create!(name: "Xpedo", frame_maker: true)
Manufacturer.create!(name: "Xtracycle", frame_maker: true)
Manufacturer.create!(name: "YST", frame_maker: true)
Manufacturer.create!(name: "Yakima", frame_maker: true)
Manufacturer.create!(name: "Yaktrax", frame_maker: true)
Manufacturer.create!(name: "Yamaguchi Bicycles", frame_maker: true)
Manufacturer.create!(name: "Yamaha", frame_maker: true)
Manufacturer.create!(name: "Yankz", frame_maker: true)
Manufacturer.create!(name: "Yeti", frame_maker: true)
Manufacturer.create!(name: "Yuba", frame_maker: true)
Manufacturer.create!(name: "Yurbuds", frame_maker: true)
Manufacturer.create!(name: "Zensah", frame_maker: true)
Manufacturer.create!(name: "Zigo", frame_maker: true)
Manufacturer.create!(name: "Zipp Speed Weaponry", frame_maker: true)
Manufacturer.create!(name: "Zoic", frame_maker: true)
Manufacturer.create!(name: "Zoom", frame_maker: true)
Manufacturer.create!(name: "Zoot", frame_maker: true)
Manufacturer.create!(name: "b'Twin", frame_maker: true)
Manufacturer.create!(name: "e*thirteen by The Hive", frame_maker: true)
Manufacturer.create!(name: "eGear", frame_maker: true)
Manufacturer.create!(name: "elete", frame_maker: true)
Manufacturer.create!(name: "epicRIDES", frame_maker: true)
Manufacturer.create!(name: "name", frame_maker: true)
Manufacturer.create!(name: "nuun", frame_maker: true)
Manufacturer.create!(name: "sixthreezero", frame_maker: true)
