# A Small sampling of manufacturers to seed!
# To get the full list download https://github.com/bikeindex/resources/blob/master/manufacturers.csv
# You can upload the csv in admin section :)
Manufacturer.create(name: "Unknown", frame_maker: true)
Manufacturer.create(name: "Other", frame_maker: true)
Manufacturer.create(name: "Giant Manufacturing",  frame_maker: true, website: "http://www.giant-bicycles.com/")
Manufacturer.create(name: "Yamaguchi Bicycles",  frame_maker: true, website: "http://www.yamaguchibike.com/content/Index")
Manufacturer.create(name: "Zipp Speed Weaponry")
Manufacturer.create(name: "WeThePeople",  frame_maker: true)
Manufacturer.create(name: "Rivendell Bicycle Works",  frame_maker: true, website: "http://www.rivbike.com/")
Manufacturer.create(name: "Soma",  frame_maker: true, website: "www.somafab.com")
Manufacturer.create(name: "Fuji",  frame_maker: true, website: "http://www.fujibikes.com/")
Manufacturer.create(name: "Schwinn",  frame_maker: true, website: "http://www.schwinnbikes.com/")
Manufacturer.create(name: "Sram",  frame_maker: false, website: "http://www.sram.com")
Manufacturer.create(name: "Doberman Bikes",  frame_maker: true, website: "https://www.facebook.com/DobermannBikes")
Manufacturer.create(name: "Surly",  frame_maker: true, website: "http://surlybikes.com")
Manufacturer.create(name: "Trek Bikes",  frame_maker: true, website: "http://www.trekbikes.com/us/en/")
Manufacturer.create(name: "KHS Bicycles",  frame_maker: true, website: "http://khsbicycles.com/")
Manufacturer.create(name: "Jamis",  frame_maker: true, website: "http://www.jamisbikes.com/usa/index.html")
Manufacturer.create(name: "Shimano",  frame_maker: false, website: "http://bike.shimano.com")
Manufacturer.create(name: "Campagnolo",  frame_maker: false, website: "http://www.campagnolo.com/")