version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  ignore:
    - dependency-name: active_model_serializers # pinned ~> 0.8.3, newer versions are slower
    - dependency-name: MailchimpMarketing
    - dependency-name: stripe
    - dependency-name: twitter
    - dependency-name: coffee-rails # deprecated CoffeeScript
    - dependency-name: carrierwave
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
