AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/AndOr:
  Enabled: false

ParameterLists:
  CountKeywordArgs: false

NumericLiterals:
  Enabled: false