AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "node_modules/**/*"

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Layout:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ParameterLists:
  CountKeywordArgs: false

Style:
  Enabled: false
