AllCops:
  TargetRubyVersion:
    2.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/AndOr:
  Enabled: false

ParameterLists:
  CountKeywordArgs: false

# https://anti-pattern.com/always-use-double-quoted-strings-in-ruby
Style/StringLiterals:
  EnforcedStyle: double_quotes # Always do it, lower cost cognitively

NumericLiterals:
  Enabled: false