AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"

FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

# I'm a fan of defining convenience methods in single lines
Style/SingleLineMethods:
  Enabled: false

# https://anti-pattern.com/always-use-double-quoted-strings-in-ruby
# All future updates should use double quotes, don't enforce so there aren't a ton of errors
Style/StringLiterals:
  EnforcedStyle: double_quotes # Always do it, lower cost cognitively
  Enabled: false

 Style/NumericPredicate:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

NumericLiterals:
  Enabled: false

ParameterLists:
  CountKeywordArgs: false

