parallel: true
format: progress

plugins:
  - standard-rails

ignore:
  - "public/**/*"
  - "node_modules/**/*"
  - "spec/vcr_cassettes/*"
  - app/models/single_sign_on.rb
  - app/uploaders/alert_image_uploader.rb
  - app/uploaders/avatar_uploader.rb
  - app/uploaders/manufacturer_logo_uploader.rb
