parallel: true
format: progress

ignore:
  - "node_modules/**/*"
  - app/models/single_sign_on.rb # Keep it the way it was originally

# Layout/ParameterAlignment:
#   EnforcedStyle: with_first_parameter
