fix: true
parallel: true
# format: progress

ignore:
  - "public/**/*"
  - "node_modules/**/*"
  - app/models/single_sign_on.rb
  - app/uploaders/alert_image_uploader.rb
  - app/uploaders/avatar_uploader.rb
