FORMAT: 1A

# Bike Index API v2
Bike Index API, V2! Because, bikes :heart:

# GET /api/v1/colors
+ Response 200 (application/json; charset=utf-8)

        {
          "colors": [
            {
              "name": "Black"
            },
            {
              "name": "Blue"
            },
            {
              "name": "Brown"
            },
            {
              "name": "Green"
            },
            {
              "name": "Orange"
            },
            {
              "name": "Pink"
            },
            {
              "name": "Purple"
            },
            {
              "name": "Red"
            },
            {
              "name": "Silver or Gray"
            },
            {
              "name": "Stickers tape or other cover-up"
            },
            {
              "name": "Teal"
            },
            {
              "name": "White"
            },
            {
              "name": "Yellow or Gold"
            }
          ]
        }