---
http_interactions:
- request:
    method: get
    uri: https://us6.api.mailchimp.com/3.0/lists/b675299293/interest-categories
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - openresty
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '2374'
      Vary:
      - Accept-Encoding
      X-Request-Id:
      - 2a198583-6126-cfd5-79b6-94d40d41c2db
      Link:
      - <https://us6.api.mailchimp.com/schema/3.0/Lists/InterestCategories/Collection.json>;
        rel="describedBy"
      Date:
      - Mon, 14 Jun 2021 22:56:16 GMT
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: '{"list_id":"b675299293","categories":[{"list_id":"b675299293","id":"2e650f9110","title":"Organization
        type","display_order":0,"type":"checkboxes","_links":[{"rel":"self","href":"https://us6.api.mailchimp.com/3.0/lists/b675299293/interest-categories/2e650f9110","method":"GET","targetSchema":"https://us6.api.mailchimp.com/schema/3.0/Definitions/Lists/InterestCategories/Response.json"},{"rel":"parent","href":"https://us6.api.mailchimp.com/3.0/lists/b675299293/interest-categories","method":"GET","targetSchema":"https://us6.api.mailchimp.com/schema/3.0/Definitions/Lists/InterestCategories/CollectionResponse.json","schema":"https://us6.api.mailchimp.com/schema/3.0/Paths/Lists/InterestCategories/Collection.json"},{"rel":"update","href":"https://us6.api.mailchimp.com/3.0/lists/b675299293/interest-categories/2e650f9110","method":"PATCH","targetSchema":"https://us6.api.mailchimp.com/schema/3.0/Definitions/Lists/InterestCategories/Response.json","schema":"https://us6.api.mailchimp.com/schema/3.0/Definitions/Lists/InterestCategories/PATCH.json"},{"rel":"delete","href":"https://us6.api.mailchimp.com/3.0/lists/b675299293/interest-categories/2e650f9110","method":"DELETE"},{"rel":"interests","href":"https://us6.api.mailchimp.com/3.0/lists/b675299293/interest-categories/2e650f9110/interests","method":"GET","targetSchema":"https://us6.api.mailchimp.com/schema/3.0/Definitions/Lists/Interests/CollectionResponse.json","schema":"https://us6.api.mailchimp.com/schema/3.0/Paths/Lists/Interests/Collection.json"}]}],"total_items":1,"_links":[{"rel":"self","href":"https://us6.api.mailchimp.com/3.0/lists/b675299293/interest-categories","method":"GET","targetSchema":"https://us6.api.mailchimp.com/schema/3.0/Definitions/Lists/InterestCategories/CollectionResponse.json","schema":"https://us6.api.mailchimp.com/schema/3.0/Paths/Lists/InterestCategories/Collection.json"},{"rel":"parent","href":"https://us6.api.mailchimp.com/3.0/lists/b675299293/","method":"GET","targetSchema":"https://us6.api.mailchimp.com/schema/3.0/Definitions/Lists/Response.json"},{"rel":"create","href":"https://us6.api.mailchimp.com/3.0/lists/b675299293/interest-categories","method":"POST","targetSchema":"https://us6.api.mailchimp.com/schema/3.0/Definitions/Lists/InterestCategories/Response.json","schema":"https://us6.api.mailchimp.com/schema/3.0/Definitions/Lists/InterestCategories/POST.json"}]}'
    http_version:
  recorded_at: Mon, 14 Jun 2021 22:56:16 GMT
recorded_with: VCR 5.0.0
