development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: bikeindex_<%= ENV.fetch("CONDUCTOR_WORKSPACE", "development") %>

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: bikeindex_production
