---
production:
  :concurrency: 10
:queues:
  - blockable # Things that can take a really long time and might get dropped if the queue backs up
  - [low_priority, 10] # Lowest priority, general things, non-user-facing
  - [carrierwave, 20] # Also includes file_caching/tsv creation
  - [notify, 200] # sending email & notifications - NOTE: has a dedicated queue
  - [high_priority, 200] # User facing updates, execute immediately - NOTE: has a dedicated queue
  
