---
production:
  :concurrency: 10
:queues:
  - update_model_audit # UpdateModelAudit can take a really long time and block things
  - [low_priority, 10] # Lowest priority, general things, non-user-facing
  - [carrierwave, 20] # Also includes file_caching/tsv creation
  - [notify, 200] # sending email & notifications
  - [high_priority, 200] # User facing updates, execute immediately
  
