test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
  public: true

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  public: true

cloudflare_dev:
  service: S3
  endpoint: <%= ENV["R2_ENDPOINT"] %>
  access_key_id: <%= ENV["R2_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["R2_ACCESS_KEY_SECRET"] %>
  bucket: bikeindex-dev
  region: auto
  public: true

cloudflare_production:
  service: S3
  endpoint: <%= ENV["R2_ENDPOINT"] %>
  access_key_id: <%= ENV["R2_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["R2_ACCESS_KEY_SECRET"] %>
  bucket: bikeindex
  region: auto
  public: true
