module StatesAndCountries
  def self.states
    [
      {name: "Alabama", abbr: "AL"},
      {name: "Alaska", abbr: "AK"},
      {name: "Arizona", abbr: "AZ"},
      {name: "Arkansas", abbr: "AR"},
      {name: "California", abbr: "CA"},
      {name: "Colorado", abbr: "CO"},
      {name: "Connecticut", abbr: "CT"},
      {name: "Delaware", abbr: "DE"},
      {name: "District of Columbia", abbr: "DC"},
      {name: "Florida", abbr: "FL"},
      {name: "Georgia", abbr: "GA"},
      {name: "Hawaii", abbr: "HI"},
      {name: "Idaho", abbr: "ID"},
      {name: "Illinois", abbr: "IL"},
      {name: "Indiana", abbr: "IN"},
      {name: "Iowa", abbr: "IA"},
      {name: "Kansas", abbr: "KS"},
      {name: "Kentucky", abbr: "KY"},
      {name: "Louisiana", abbr: "LA"},
      {name: "Maine", abbr: "ME"},
      {name: "Maryland", abbr: "MD"},
      {name: "Massachusetts", abbr: "MA"},
      {name: "Michigan", abbr: "MI"},
      {name: "Minnesota", abbr: "MN"},
      {name: "Mississippi", abbr: "MS"},
      {name: "Missouri", abbr: "MO"},
      {name: "Montana", abbr: "MT"},
      {name: "Nebraska", abbr: "NE"},
      {name: "Nevada", abbr: "NV"},
      {name: "New Hampshire", abbr: "NH"},
      {name: "New Jersey", abbr: "NJ"},
      {name: "New Mexico", abbr: "NM"},
      {name: "New York", abbr: "NY"},
      {name: "North Carolina", abbr: "NC"},
      {name: "North Dakota", abbr: "ND"},
      {name: "Ohio", abbr: "OH"},
      {name: "Oklahoma", abbr: "OK"},
      {name: "Oregon", abbr: "OR"},
      {name: "Pennsylvania", abbr: "PA"},
      {name: "Puerto Rico", abbr: "PR"},
      {name: "Rhode Island", abbr: "RI"},
      {name: "South Carolina", abbr: "SC"},
      {name: "South Dakota", abbr: "SD"},
      {name: "Tennessee", abbr: "TN"},
      {name: "Texas", abbr: "TX"},
      {name: "Utah", abbr: "UT"},
      {name: "Vermont", abbr: "VT"},
      {name: "Virginia", abbr: "VA"},
      {name: "Washington", abbr: "WA"},
      {name: "West Virginia", abbr: "WV"},
      {name: "Wisconsin", abbr: "WI"},
      {name: "Wyoming", abbr: "WY"}
    ]
  end

  def self.countries
    [
      {name: "Afghanistan", iso: "AF", self_name: "افغانستان"},
      {name: "Albania", iso: "AL", self_name: "Shqipëria"},
      {name: "Algeria", iso: "DZ", self_name: "الجزائر"},
      {name: "American Samoa", iso: "AS"},
      {name: "Andorra", iso: "AD"},
      {name: "Angola", iso: "AO"},
      {name: "Anguilla", iso: "AI"},
      {name: "Antarctica", iso: "AQ"},
      {name: "Antigua and Barbuda", iso: "AG"},
      {name: "Argentina", iso: "AR"},
      {name: "Armenia", iso: "AM", self_name: "Հայաստան"},
      {name: "Aruba", iso: "AW"},
      {name: "Australia", iso: "AU"},
      {name: "Austria", iso: "AT", self_name: "Österreich"},
      {name: "Azerbaijan", iso: "AZ", self_name: "Azərbaycan"},
      {name: "Bahamas", iso: "BS"},
      {name: "Bahrain", iso: "BH", self_name: "البحرين"},
      {name: "Bangladesh", iso: "BD", self_name: "বাংলাদেশ"},
      {name: "Barbados", iso: "BB"},
      {name: "Belarus", iso: "BY", self_name: "Беларусь"},
      {name: "Belgium", iso: "BE", self_name: "België"},
      {name: "Belize", iso: "BZ"},
      {name: "Benin", iso: "BJ", self_name: "Bénin"},
      {name: "Bermuda", iso: "BM"},
      {name: "Bhutan", iso: "BT", self_name: "འབྲུག་ཡུལ"},
      {name: "Bolivia", iso: "BO"},
      {name: "Bosnia and Herzegovina", iso: "BA", self_name: "Bosna i Hercegovina"},
      {name: "Botswana", iso: "BW"},
      {name: "Bouvet Island", iso: "BV"},
      {name: "Brazil", iso: "BR", self_name: "Brasil"},
      {name: "British Indian Ocean Territory", iso: "IO"},
      {name: "Brunei Darussalam", iso: "BN"},
      {name: "Bulgaria", iso: "BG", self_name: "България"},
      {name: "Burkina Faso", iso: "BF"},
      {name: "Burundi", iso: "BI"},
      {name: "Cambodia", iso: "KH", self_name: "កម្ពុជា"},
      {name: "Cameroon", iso: "CM", self_name: "Cameroun"},
      {name: "Canada", iso: "CA"},
      {name: "Cape Verde", iso: "CV", self_name: "Cabo Verde"},
      {name: "Cayman Islands", iso: "KY"},
      {name: "Central African Republic", iso: "CF", self_name: "République centrafricaine"},
      {name: "Chad", iso: "TD", self_name: "Tchad"},
      {name: "Chile", iso: "CL"},
      {name: "China", iso: "CN", self_name: "中国"},
      {name: "Christmas Island", iso: "CX"},
      {name: "Cocos (Keeling) Islands", iso: "CC"},
      {name: "Colombia", iso: "CO"},
      {name: "Comoros", iso: "KM", self_name: "Komori"},
      {name: "Congo", iso: "CG"},
      {name: "Congo, The Democratic Republic of The", iso: "CD"},
      {name: "Cook Islands", iso: "CK"},
      {name: "Costa Rica", iso: "CR"},
      {name: "Cote D'ivoire", iso: "CI", self_name: "Côte d'Ivoire"},
      {name: "Croatia", iso: "HR", self_name: "Hrvatska"},
      {name: "Cuba", iso: "CU"},
      {name: "Cyprus", iso: "CY", self_name: "Κύπρος"},
      {name: "Czech Republic", iso: "CZ", self_name: "Česko"},
      {name: "Denmark", iso: "DK", self_name: "Danmark"},
      {name: "Djibouti", iso: "DJ"},
      {name: "Dominica", iso: "DM"},
      {name: "Dominican Republic", iso: "DO", self_name: "República Dominicana"},
      {name: "Ecuador", iso: "EC"},
      {name: "Egypt", iso: "EG", self_name: "مصر"},
      {name: "El Salvador", iso: "SV"},
      {name: "Equatorial Guinea", iso: "GQ", self_name: "Guinea Ecuatorial"},
      {name: "Eritrea", iso: "ER", self_name: "ኤርትራ"},
      {name: "Estonia", iso: "EE", self_name: "Eesti"},
      {name: "Ethiopia", iso: "ET", self_name: "ኢትዮጵያ"},
      {name: "Falkland Islands (Malvinas", iso: "FK"},
      {name: "Faroe Islands", iso: "FO", self_name: "Føroyar"},
      {name: "Fiji", iso: "FJ"},
      {name: "Finland", iso: "FI", self_name: "Suomi"},
      {name: "France", iso: "FR"},
      {name: "French Guiana", iso: "GF"},
      {name: "French Polynesia", iso: "PF"},
      {name: "French Southern Territories", iso: "TF"},
      {name: "Gabon", iso: "GA"},
      {name: "Gambia", iso: "GM"},
      {name: "Georgia", iso: "GE", self_name: "საქართველო"},
      {name: "Germany", iso: "DE", self_name: "Deutschland"},
      {name: "Ghana", iso: "GH"},
      {name: "Gibraltar", iso: "GI"},
      {name: "Greece", iso: "GR", self_name: "Ελλάδα"},
      {name: "Greenland", iso: "GL", self_name: "Kalaallit Nunaat"},
      {name: "Grenada", iso: "GD"},
      {name: "Guadeloupe", iso: "GP"},
      {name: "Guam", iso: "GU"},
      {name: "Guatemala", iso: "GT"},
      {name: "Guernsey", iso: "GG"},
      {name: "Guinea", iso: "GN", self_name: "Guinée"},
      {name: "Guinea-bissau", iso: "GW", self_name: "Guiné-Bissau"},
      {name: "Guyana", iso: "GY"},
      {name: "Haiti", iso: "HT", self_name: "Haïti"},
      {name: "Heard Island and Mcdonald Islands", iso: "HM"},
      {name: "Holy See (Vatican City State", iso: "VA"},
      {name: "Honduras", iso: "HN"},
      {name: "Hong Kong", iso: "HK", self_name: "香港"},
      {name: "Hungary", iso: "HU", self_name: "Magyarország"},
      {name: "Iceland", iso: "IS", self_name: "Ísland"},
      {name: "India", iso: "IN", self_name: "भारत"},
      {name: "Indonesia", iso: "ID"},
      {name: "Iran, Islamic Republic of", iso: "IR", self_name: "ایران"},
      {name: "Iraq", iso: "IQ", self_name: "العراق"},
      {name: "Ireland", iso: "IE", self_name: "Éire"},
      {name: "Isle of Man", iso: "IM"},
      {name: "Israel", iso: "IL", self_name: "ישראל"},
      {name: "Italy", iso: "IT", self_name: "Italia"},
      {name: "Jamaica", iso: "JM"},
      {name: "Japan", iso: "JP", self_name: "日本"},
      {name: "Jersey", iso: "JE"},
      {name: "Jordan", iso: "JO", self_name: "الأردن"},
      {name: "Kazakhstan", iso: "KZ", self_name: "Қазақстан"},
      {name: "Kenya", iso: "KE"},
      {name: "Kiribati", iso: "KI"},
      {name: "Korea, Democratic People's Republic of", iso: "KP", self_name: "조선"},
      {name: "Korea, Republic of", iso: "KR", self_name: "대한민국"},
      {name: "Kuwait", iso: "KW", self_name: "الكويت"},
      {name: "Kyrgyzstan", iso: "KG", self_name: "Кыргызстан"},
      {name: "Lao People's Democratic Republic", iso: "LA", self_name: "ລາວ"},
      {name: "Latvia", iso: "LV", self_name: "Latvija"},
      {name: "Lebanon", iso: "LB", self_name: "لبنان"},
      {name: "Lesotho", iso: "LS"},
      {name: "Liberia", iso: "LR"},
      {name: "Libyan Arab Jamahiriya", iso: "LY", self_name: "ليبيا"},
      {name: "Liechtenstein", iso: "LI"},
      {name: "Lithuania", iso: "LT", self_name: "Lietuva"},
      {name: "Luxembourg", iso: "LU", self_name: "Lëtzebuerg"},
      {name: "Macao", iso: "MO", self_name: "澳門"},
      {name: "Macedonia, The Former Yugoslav Republic of", iso: "MK", self_name: "Македонија"},
      {name: "Madagascar", iso: "MG", self_name: "Madagasikara"},
      {name: "Malawi", iso: "MW"},
      {name: "Malaysia", iso: "MY"},
      {name: "Maldives", iso: "MV", self_name: "ދިވެހިރާއްޖެ"},
      {name: "Mali", iso: "ML"},
      {name: "Malta", iso: "MT"},
      {name: "Marshall Islands", iso: "MH"},
      {name: "Martinique", iso: "MQ"},
      {name: "Mauritania", iso: "MR", self_name: "موريتانيا"},
      {name: "Mauritius", iso: "MU"},
      {name: "Mayotte", iso: "YT"},
      {name: "Mexico", iso: "MX", self_name: "México"},
      {name: "Micronesia, Federated States of", iso: "FM"},
      {name: "Moldova, Republic of", iso: "MD"},
      {name: "Monaco", iso: "MC"},
      {name: "Mongolia", iso: "MN", self_name: "Монгол Улс"},
      {name: "Montenegro", iso: "ME", self_name: "Crna Gora"},
      {name: "Montserrat", iso: "MS"},
      {name: "Morocco", iso: "MA", self_name: "المغرب"},
      {name: "Mozambique", iso: "MZ", self_name: "Moçambique"},
      {name: "Myanmar", iso: "MM", self_name: "မြန်မာ"},
      {name: "Namibia", iso: "NA"},
      {name: "Nauru", iso: "NR", self_name: "Naoero"},
      {name: "Nepal", iso: "NP", self_name: "नेपाल"},
      {name: "Netherlands", iso: "NL", self_name: "Nederland"},
      {name: "Netherlands Antilles", iso: "AN"},
      {name: "New Caledonia", iso: "NC"},
      {name: "New Zealand", iso: "NZ", self_name: "Aotearoa"},
      {name: "Nicaragua", iso: "NI"},
      {name: "Niger", iso: "NE"},
      {name: "Nigeria", iso: "NG"},
      {name: "Niue", iso: "NU"},
      {name: "Norfolk Island", iso: "NF"},
      {name: "Northern Mariana Islands", iso: "MP"},
      {name: "Norway", iso: "NO", self_name: "Norge"},
      {name: "Oman", iso: "OM", self_name: "عُمان"},
      {name: "Pakistan", iso: "PK", self_name: "پاکستان"},
      {name: "Palau", iso: "PW", self_name: "Belau"},
      {name: "Palestinian Territory, Occupied", iso: "PS", self_name: "فلسطين"},
      {name: "Panama", iso: "PA", self_name: "Panamá"},
      {name: "Papua New Guinea", iso: "PG"},
      {name: "Paraguay", iso: "PY"},
      {name: "Peru", iso: "PE", self_name: "Perú"},
      {name: "Philippines", iso: "PH", self_name: "Pilipinas"},
      {name: "Pitcairn", iso: "PN"},
      {name: "Poland", iso: "PL", self_name: "Polska"},
      {name: "Portugal", iso: "PT"},
      {name: "Puerto Rico", iso: "PR"},
      {name: "Qatar", iso: "QA", self_name: "قطر"},
      {name: "Reunion", iso: "RE"},
      {name: "Romania", iso: "RO", self_name: "România"},
      {name: "Russian Federation", iso: "RU", self_name: "Россия"},
      {name: "Rwanda", iso: "RW"},
      {name: "Saint Helena", iso: "SH"},
      {name: "Saint Kitts and Nevis", iso: "KN"},
      {name: "Saint Lucia", iso: "LC"},
      {name: "Saint Pierre and Miquelon", iso: "PM"},
      {name: "Saint Vincent and The Grenadines", iso: "VC"},
      {name: "Samoa", iso: "WS"},
      {name: "San Marino", iso: "SM"},
      {name: "Sao Tome and Principe", iso: "ST", self_name: "São Tomé e Príncipe"},
      {name: "Saudi Arabia", iso: "SA", self_name: "السعودية"},
      {name: "Senegal", iso: "SN", self_name: "Sénégal"},
      {name: "Serbia", iso: "RS", self_name: "Србија"},
      {name: "Seychelles", iso: "SC"},
      {name: "Sierra Leone", iso: "SL"},
      {name: "Singapore", iso: "SG"},
      {name: "Slovakia", iso: "SK", self_name: "Slovensko"},
      {name: "Slovenia", iso: "SI", self_name: "Slovenija"},
      {name: "Solomon Islands", iso: "SB"},
      {name: "Somalia", iso: "SO", self_name: "Soomaaliya"},
      {name: "South Africa", iso: "ZA"},
      {name: "South Georgia and The South Sandwich Islands", iso: "GS"},
      {name: "Spain", iso: "ES", self_name: "España"},
      {name: "Sri Lanka", iso: "LK", self_name: "ශ්‍රී ලංකාව"},
      {name: "Sudan", iso: "SD", self_name: "السودان"},
      {name: "Suriname", iso: "SR"},
      {name: "Svalbard and Jan Mayen", iso: "SJ"},
      {name: "Swaziland", iso: "SZ", self_name: "eSwatini"},
      {name: "Sweden", iso: "SE", self_name: "Sverige"},
      {name: "Switzerland", iso: "CH", self_name: "Schweiz"},
      {name: "Syrian Arab Republic", iso: "SY", self_name: "سوريا"},
      {name: "Taiwan", iso: "TW", self_name: "臺灣"},
      {name: "Tajikistan", iso: "TJ", self_name: "Тоҷикистон"},
      {name: "Tanzania, United Republic of", iso: "TZ"},
      {name: "Thailand", iso: "TH", self_name: "ไทย"},
      {name: "Timor-leste", iso: "TL"},
      {name: "Togo", iso: "TG"},
      {name: "Tokelau", iso: "TK"},
      {name: "Tonga", iso: "TO"},
      {name: "Trinidad and Tobago", iso: "TT"},
      {name: "Tunisia", iso: "TN", self_name: "تونس"},
      {name: "Turkey", iso: "TR", self_name: "Türkiye"},
      {name: "Turkmenistan", iso: "TM", self_name: "Türkmenistan"},
      {name: "Turks and Caicos Islands", iso: "TC"},
      {name: "Tuvalu", iso: "TV"},
      {name: "Uganda", iso: "UG"},
      {name: "Ukraine", iso: "UA", self_name: "Україна"},
      {name: "United Arab Emirates", iso: "AE", self_name: "الإمارات"},
      {name: "United Kingdom", iso: "GB"},
      {name: "United States", iso: "US"},
      {name: "United States Minor Outlying Islands", iso: "UM"},
      {name: "Uruguay", iso: "UY"},
      {name: "Uzbekistan", iso: "UZ", self_name: "Oʻzbekiston"},
      {name: "Vanuatu", iso: "VU"},
      {name: "Venezuela", iso: "VE"},
      {name: "Viet Nam", iso: "VN", self_name: "Việt Nam"},
      {name: "Virgin Islands, British", iso: "VG"},
      {name: "Virgin Islands, U.S", iso: "VI"},
      {name: "Wallis and Futuna", iso: "WF"},
      {name: "Western Sahara", iso: "EH", self_name: "الصحراء الغربية"},
      {name: "Yemen", iso: "YE", self_name: "اليمن"},
      {name: "Zambia", iso: "ZM"},
      {name: "Zimbabwe", iso: "ZW"}
    ]
  end
end
